/**
 * World folk tales — long, read-aloud children's stories (~8–10 minutes each)
 * retold in the platform's own words from classic PUBLIC-DOMAIN folklore from
 * around the world (owner: "cerita anak berkualitas, agak panjang 10 menitan,
 * dari seluruh dunia"). Bilingual EN/ID like the rest of the library, each with
 * a gentle comprehension quiz. Concatenated into STORIES (see stories.ts) so
 * `npm run generate:seed` writes them straight into seed/seed.sql.
 */
import type { Story } from "./stories";

export const WORLD_STORIES: Story[] = [
  {
    slug: "the-lion-and-the-mouse",
    titleEn: "The Lion and the Mouse",
    titleId: "Singa dan Tikus Kecil",
    descriptionEn: "A tiny mouse promises to help a mighty lion — and one day, against all odds, she keeps her word.",
    descriptionId: "Seekor tikus kecil berjanji menolong singa yang perkasa — dan suatu hari, ia benar-benar menepatinya.",
    categorySlug: "moral-stories",
    authorSlug: "axto-creative-team",
    coverEmoji: "🦁",
    coverPalette: "sunrise",
    ageMin: 3,
    ageMax: 8,
    isPremium: false,
    pages: [
      { illustrationSeed: "lion-mouse-1", textEn: "Deep in the golden grasslands of Africa lived a great lion. He was the strongest animal for miles around, and when he roared, even the wind seemed to hold its breath.", textId: "Jauh di padang rumput keemasan Afrika, hiduplah seekor singa besar. Ia hewan terkuat sejauh mata memandang, dan ketika ia mengaum, angin pun seakan menahan napas." },
      { illustrationSeed: "lion-mouse-2", textEn: "One warm afternoon, the lion lay sleeping under a shady acacia tree, his huge paws stretched out in the soft grass.", textId: "Suatu siang yang hangat, singa itu tertidur di bawah pohon akasia yang rindang, cakar besarnya terjulur di rerumputan lembut." },
      { illustrationSeed: "lion-mouse-3", textEn: "A little mouse, hurrying home with a seed for her supper, did not see the sleeping lion. She scampered right up his warm back — and woke him with a start!", textId: "Seekor tikus kecil yang tergesa pulang membawa biji untuk makan malamnya tak melihat singa yang tidur. Ia berlari tepat ke punggung hangat sang singa — dan membangunkannya!" },
      { illustrationSeed: "lion-mouse-4", textEn: "The lion's giant paw came down and trapped her gently against the ground. 'How dare you wake me!' he growled. The mouse trembled from her whiskers to her tail.", textId: "Cakar raksasa singa turun dan menahannya lembut ke tanah. 'Berani sekali kau membangunkanku!' geramnya. Tikus itu gemetar dari kumis sampai ekornya." },
      { illustrationSeed: "lion-mouse-5", textEn: "'Please, mighty lion, let me go,' she squeaked. 'I am only small, and I meant no harm. If you set me free, perhaps one day I can help you.'", textId: "'Tolong, singa yang perkasa, lepaskan aku,' cicitnya. 'Aku hanya kecil dan tak bermaksud jahat. Jika kau membebaskanku, mungkin suatu hari aku bisa menolongmu.'" },
      { illustrationSeed: "lion-mouse-6", textEn: "The lion laughed a great rumbling laugh. 'You? Help me? What a funny little thought!' But he was in a kind mood, so he lifted his paw and let her go.", textId: "Singa itu tertawa menggelegar. 'Kau? Menolongku? Sungguh lucu!' Namun hatinya sedang baik, maka ia mengangkat cakarnya dan melepaskan tikus itu." },
      { illustrationSeed: "lion-mouse-7", textEn: "'Thank you, thank you!' cried the mouse, and she darted away into the grass, her small heart pounding with relief.", textId: "'Terima kasih, terima kasih!' seru tikus itu, lalu melesat ke rerumputan, jantung kecilnya berdebar lega." },
      { illustrationSeed: "lion-mouse-8", textEn: "Many days passed. Then one evening, hunters came to the grasslands. They spread a strong rope net between the trees, and the great lion walked straight into their trap.", textId: "Berhari-hari berlalu. Lalu suatu senja, pemburu datang ke padang. Mereka membentangkan jaring tali yang kuat di antara pohon, dan singa besar itu berjalan tepat ke perangkap." },
      { illustrationSeed: "lion-mouse-9", textEn: "The more he struggled, the tighter the net held him. He roared and roared, but the ropes would not break. For the first time, the mighty lion felt truly helpless.", textId: "Semakin ia meronta, semakin erat jaring itu mengikatnya. Ia mengaum berkali-kali, tetapi tali itu tak putus. Untuk pertama kalinya, singa perkasa itu merasa benar-benar tak berdaya." },
      { illustrationSeed: "lion-mouse-10", textEn: "Far away, the little mouse heard the desperate roars. 'That is my friend the lion!' she said, and she ran as fast as her tiny legs could carry her.", textId: "Jauh di sana, tikus kecil mendengar aumannya yang putus asa. 'Itu sahabatku, sang singa!' katanya, lalu ia berlari secepat kaki kecilnya bisa membawanya." },
      { illustrationSeed: "lion-mouse-11", textEn: "She reached the net and began to gnaw — nibble, nibble, nibble — with her sharp little teeth. One rope snapped. Then another. Then another.", textId: "Ia sampai di jaring dan mulai menggerogoti — kriuk, kriuk, kriuk — dengan gigi kecilnya yang tajam. Satu tali putus. Lalu satu lagi. Lalu satu lagi." },
      { illustrationSeed: "lion-mouse-12", textEn: "At last the net fell open, and the great lion stepped free. He looked down at the tiny mouse in wonder. 'You truly did help me,' he said softly.", textId: "Akhirnya jaring itu terbuka, dan singa besar melangkah bebas. Ia menunduk memandang tikus mungil itu dengan takjub. 'Kau sungguh menolongku,' katanya lembut." },
      { illustrationSeed: "lion-mouse-13", textEn: "From that day on, the lion and the mouse were the closest of friends. And the lion never again laughed at anyone for being small.", textId: "Sejak hari itu, singa dan tikus menjadi sahabat terdekat. Dan singa tak pernah lagi menertawakan siapa pun karena tubuhnya kecil." },
      { illustrationSeed: "lion-mouse-14", textEn: "For kindness is never wasted, and even the smallest friend can do the greatest thing. The end.", textId: "Sebab kebaikan tak pernah sia-sia, dan sahabat sekecil apa pun bisa melakukan hal terbesar. Tamat." },
    ],
    quiz: [
      { questionEn: "Why did the lion let the mouse go?", questionId: "Mengapa singa melepaskan tikus?", optionsEn: ["He was hungry", "He was in a kind mood", "The mouse ran away", "He was afraid"], optionsId: ["Ia lapar", "Hatinya sedang baik", "Tikus melarikan diri", "Ia takut"], correctIndex: 1 },
      { questionEn: "How did the mouse save the lion?", questionId: "Bagaimana tikus menyelamatkan singa?", optionsEn: ["She roared loudly", "She called the hunters", "She gnawed through the net", "She dug a hole"], optionsId: ["Ia mengaum keras", "Ia memanggil pemburu", "Ia menggerogoti jaring", "Ia menggali lubang"], correctIndex: 2 },
      { questionEn: "What is the lesson of the story?", questionId: "Apa pelajaran dari cerita ini?", optionsEn: ["Big is always best", "Kindness is never wasted", "Never sleep outside", "Run fast"], optionsId: ["Besar selalu terbaik", "Kebaikan tak pernah sia-sia", "Jangan tidur di luar", "Berlari cepat"], correctIndex: 1 },
    ],
  },
  {
    slug: "momotaro-the-peach-boy",
    titleEn: "Momotaro, the Peach Boy",
    titleId: "Momotaro, Anak dari Buah Persik",
    descriptionEn: "A brave boy born from a giant peach sets off with three animal friends to bring peace back to his island.",
    descriptionId: "Anak pemberani yang lahir dari buah persik raksasa berpetualang bersama tiga sahabat hewan untuk membawa kedamaian kembali ke pulaunya.",
    categorySlug: "adventure",
    authorSlug: "axto-creative-team",
    coverEmoji: "🍑",
    coverPalette: "sunrise",
    ageMin: 4,
    ageMax: 9,
    isPremium: false,
    pages: [
      { illustrationSeed: "momo-1", textEn: "Long ago in Japan, an old woodcutter and his wife lived at the edge of a quiet village. They were kind and gentle, but they had no children, and their little house often felt empty.", textId: "Dahulu kala di Jepang, seorang penebang kayu tua dan istrinya tinggal di tepi desa yang tenang. Mereka baik dan lembut, tetapi tak punya anak, dan rumah kecil mereka sering terasa sepi." },
      { illustrationSeed: "momo-2", textEn: "One morning, while the old woman washed clothes by the river, an enormous peach came bobbing down the water — the biggest peach she had ever seen.", textId: "Suatu pagi, ketika nenek mencuci pakaian di sungai, sebuah buah persik raksasa hanyut di air — persik terbesar yang pernah ia lihat." },
      { illustrationSeed: "momo-3", textEn: "She carried it home, and when the old man raised his knife to slice it, the peach split open by itself — and inside sat a healthy, laughing baby boy!", textId: "Ia membawanya pulang, dan ketika kakek mengangkat pisau untuk membelahnya, persik itu terbuka dengan sendirinya — dan di dalamnya duduk seorang bayi laki-laki yang sehat dan tertawa!" },
      { illustrationSeed: "momo-4", textEn: "'A gift from heaven!' they cried with joy. They named him Momotaro, which means Peach Boy, and raised him with all their love.", textId: "'Anugerah dari langit!' seru mereka penuh gembira. Mereka menamainya Momotaro, yang berarti Anak Persik, dan membesarkannya dengan segenap cinta." },
      { illustrationSeed: "momo-5", textEn: "Momotaro grew strong and kind. But across the sea lay Ogre Island, where fierce ogres sailed out to trouble the villages and take what was not theirs.", textId: "Momotaro tumbuh kuat dan baik hati. Namun di seberang laut ada Pulau Raksasa, tempat para raksasa buas berlayar untuk mengganggu desa dan merampas yang bukan milik mereka." },
      { illustrationSeed: "momo-6", textEn: "When he was old enough, Momotaro said, 'I will sail to Ogre Island and ask the ogres to stop, so our people can live in peace.' His parents packed him millet dumplings for the journey.", textId: "Ketika cukup besar, Momotaro berkata, 'Aku akan berlayar ke Pulau Raksasa dan meminta mereka berhenti, agar rakyat kita hidup damai.' Orang tuanya membekali kue millet untuk perjalanannya." },
      { illustrationSeed: "momo-7", textEn: "On the road he met a spotted dog. 'Where are you going, Momotaro?' 'To Ogre Island, for peace.' 'Give me a dumpling and I will come too!' So they walked on together.", textId: "Di jalan ia bertemu anjing belang. 'Mau ke mana, Momotaro?' 'Ke Pulau Raksasa, demi kedamaian.' 'Beri aku sekue dan aku ikut!' Maka mereka berjalan bersama." },
      { illustrationSeed: "momo-8", textEn: "Next came a clever monkey, and then a bright-eyed pheasant. Each shared a dumpling, and each joined the quest. Now they were four brave friends.", textId: "Lalu datang seekor monyet cerdik, dan seekor burung pegar bermata cerah. Masing-masing berbagi kue, dan masing-masing ikut serta. Kini mereka berempat sahabat pemberani." },
      { illustrationSeed: "momo-9", textEn: "They built a little boat and rowed across the wide blue sea. The pheasant flew ahead to scout, the monkey climbed the mast, and the dog watched the waves.", textId: "Mereka membuat perahu kecil dan mendayung menyeberangi laut biru yang luas. Pegar terbang memandu, monyet memanjat tiang, dan anjing mengawasi ombak." },
      { illustrationSeed: "momo-10", textEn: "At last they reached Ogre Island, ringed by tall black walls. The ogres laughed from their fortress. 'Go home, little boy!' they shouted.", textId: "Akhirnya mereka sampai di Pulau Raksasa, dikelilingi tembok hitam yang tinggi. Para raksasa tertawa dari benteng mereka. 'Pulanglah, anak kecil!' teriak mereka." },
      { illustrationSeed: "momo-11", textEn: "But Momotaro and his friends worked as a team. The pheasant swooped and distracted the ogres, the monkey unlocked the gate, and the dog and Momotaro walked bravely inside.", textId: "Namun Momotaro dan sahabatnya bekerja sebagai satu tim. Pegar menukik mengalihkan perhatian raksasa, monyet membuka gerbang, dan anjing bersama Momotaro melangkah masuk dengan berani." },
      { illustrationSeed: "momo-12", textEn: "The ogre king was surprised by their courage and teamwork. 'We surrender!' he said. 'We are sorry for the trouble we caused.'", textId: "Raja raksasa terkejut oleh keberanian dan kerja sama mereka. 'Kami menyerah!' katanya. 'Kami minta maaf atas kekacauan yang kami buat.'" },
      { illustrationSeed: "momo-13", textEn: "Momotaro did not wish to be cruel. 'Return what you have taken, and promise to trouble the villages no more.' The ogres agreed and gave back every stolen treasure.", textId: "Momotaro tak ingin kejam. 'Kembalikan yang kalian rampas, dan berjanjilah tak lagi mengganggu desa.' Para raksasa setuju dan mengembalikan setiap harta yang mereka curi." },
      { illustrationSeed: "momo-14", textEn: "Momotaro and his three friends sailed home as heroes. The village celebrated, and the old couple hugged their brave Peach Boy with happy tears.", textId: "Momotaro dan tiga sahabatnya berlayar pulang sebagai pahlawan. Desa bersukacita, dan pasangan tua itu memeluk Anak Persik pemberani mereka dengan air mata bahagia." },
      { illustrationSeed: "momo-15", textEn: "And from that day, the island lived in peace — because Momotaro knew that courage and good friends can solve even the biggest troubles. The end.", textId: "Dan sejak hari itu, pulau itu hidup damai — sebab Momotaro tahu bahwa keberanian dan sahabat yang baik dapat mengatasi masalah terbesar sekalipun. Tamat." },
    ],
    quiz: [
      { questionEn: "Where was Momotaro found?", questionId: "Di mana Momotaro ditemukan?", optionsEn: ["In a basket", "Inside a giant peach", "Under a tree", "In a boat"], optionsId: ["Dalam keranjang", "Di dalam persik raksasa", "Di bawah pohon", "Di perahu"], correctIndex: 1 },
      { questionEn: "Who joined Momotaro on his journey?", questionId: "Siapa yang menemani Momotaro?", optionsEn: ["A dog, a monkey, and a pheasant", "Three ogres", "His teacher", "No one"], optionsId: ["Anjing, monyet, dan pegar", "Tiga raksasa", "Gurunya", "Tak seorang pun"], correctIndex: 0 },
      { questionEn: "How did they defeat the ogres?", questionId: "Bagaimana mereka mengalahkan raksasa?", optionsEn: ["By fighting alone", "With teamwork", "By running away", "With magic"], optionsId: ["Bertarung sendiri", "Dengan kerja sama", "Dengan melarikan diri", "Dengan sihir"], correctIndex: 1 },
    ],
  },
  {
    slug: "anansi-and-the-pot-of-wisdom",
    titleEn: "Anansi and the Pot of Wisdom",
    titleId: "Anansi dan Periuk Kebijaksanaan",
    descriptionEn: "A clever spider tries to keep all the world's wisdom for himself — and learns something wiser than he expected.",
    descriptionId: "Laba-laba cerdik berusaha menyimpan semua kebijaksanaan dunia untuk dirinya sendiri — lalu belajar sesuatu yang lebih bijak dari dugaannya.",
    categorySlug: "moral-stories",
    authorSlug: "axto-creative-team",
    coverEmoji: "🕷️",
    coverPalette: "forest",
    ageMin: 4,
    ageMax: 9,
    isPremium: false,
    pages: [
      { illustrationSeed: "anansi-1", textEn: "In the warm forests of West Africa, there lived a clever spider named Anansi. He loved to know things — more than anyone else in the whole world.", textId: "Di hutan hangat Afrika Barat, hiduplah laba-laba cerdik bernama Anansi. Ia suka mengetahui banyak hal — lebih dari siapa pun di seluruh dunia." },
      { illustrationSeed: "anansi-2", textEn: "One day Anansi had an idea. 'If I gather ALL the wisdom in the world into one pot,' he thought, 'then I will be the wisest of all, and everyone will need me.'", textId: "Suatu hari Anansi punya gagasan. 'Jika kukumpulkan SEMUA kebijaksanaan dunia ke dalam satu periuk,' pikirnya, 'aku akan menjadi yang paling bijak, dan semua orang membutuhkanku.'" },
      { illustrationSeed: "anansi-3", textEn: "So he traveled far and wide, collecting wise sayings, clever ideas, and useful knowledge, and he poured every drop into a great clay pot.", textId: "Maka ia mengembara jauh, mengumpulkan kata-kata bijak, ide cerdas, dan pengetahuan berguna, lalu menuang setiap tetesnya ke dalam periuk tanah liat yang besar." },
      { illustrationSeed: "anansi-4", textEn: "When the pot was full, Anansi wanted to hide it where no one could ever reach it. 'I will keep it at the very top of the tallest tree,' he decided.", textId: "Ketika periuk itu penuh, Anansi ingin menyembunyikannya di tempat yang tak terjangkau siapa pun. 'Akan kusimpan di puncak pohon tertinggi,' putusnya." },
      { illustrationSeed: "anansi-5", textEn: "He tied the heavy pot to the front of his belly and began to climb. But the pot kept bumping against the trunk and getting in his way.", textId: "Ia mengikat periuk berat itu di depan perutnya dan mulai memanjat. Namun periuk itu terus terbentur batang pohon dan menghalangi jalannya." },
      { illustrationSeed: "anansi-6", textEn: "Again and again he slipped back down. The pot was simply too big and awkward to carry up the front of him. Anansi grew tired and cross.", textId: "Berulang kali ia melorot turun. Periuk itu terlalu besar dan menyusahkan untuk dibawa di depan tubuhnya. Anansi menjadi lelah dan kesal." },
      { illustrationSeed: "anansi-7", textEn: "Down below, his young son had been watching quietly. 'Father,' he called up, 'wouldn't it be easier to tie the pot on your BACK? Then you could climb freely.'", textId: "Di bawah, anaknya yang kecil memperhatikan dengan tenang. 'Ayah,' serunya, 'bukankah lebih mudah mengikat periuk di PUNGGUNG? Agar Ayah bisa memanjat dengan leluasa.'" },
      { illustrationSeed: "anansi-8", textEn: "Anansi stopped. The idea was so simple — and so clever — and it had come from his little son, not from the great pot of wisdom at all.", textId: "Anansi terdiam. Gagasan itu begitu sederhana — dan begitu cerdas — dan datang dari anak kecilnya, bukan dari periuk kebijaksanaan yang besar itu." },
      { illustrationSeed: "anansi-9", textEn: "'I gathered all the wisdom in the world,' Anansi said slowly, 'yet my own son knew something I did not. Wisdom cannot belong to just one person.'", textId: "'Aku mengumpulkan semua kebijaksanaan dunia,' kata Anansi perlahan, 'namun anakku sendiri tahu sesuatu yang tak kuketahui. Kebijaksanaan tak bisa menjadi milik satu orang saja.'" },
      { illustrationSeed: "anansi-10", textEn: "In that moment Anansi understood. He lifted the pot high and let it tip. The wisdom spilled out and scattered on the wind, drifting to every corner of the earth.", textId: "Saat itu Anansi mengerti. Ia mengangkat periuk itu tinggi-tinggi dan menumpahkannya. Kebijaksanaan tumpah dan berhamburan tertiup angin, melayang ke setiap sudut bumi." },
      { illustrationSeed: "anansi-11", textEn: "That is why, to this day, a little bit of wisdom can be found in everyone — in the old and the young, the big and the small.", textId: "Itulah sebabnya, hingga kini, sedikit kebijaksanaan bisa ditemukan pada setiap orang — pada yang tua dan yang muda, yang besar dan yang kecil." },
      { illustrationSeed: "anansi-12", textEn: "And Anansi learned the wisest lesson of all: that we grow wiser not by keeping knowledge to ourselves, but by sharing it. The end.", textId: "Dan Anansi belajar pelajaran paling bijak: bahwa kita menjadi lebih bijak bukan dengan menyimpan pengetahuan sendiri, melainkan dengan membagikannya. Tamat." },
    ],
    quiz: [
      { questionEn: "What did Anansi try to collect?", questionId: "Apa yang Anansi coba kumpulkan?", optionsEn: ["Gold coins", "All the wisdom in the world", "Ripe fruit", "Spider webs"], optionsId: ["Koin emas", "Semua kebijaksanaan dunia", "Buah matang", "Jaring laba-laba"], correctIndex: 1 },
      { questionEn: "Who gave Anansi the clever idea?", questionId: "Siapa yang memberi Anansi ide cerdas?", optionsEn: ["A wise king", "His young son", "A bird", "No one"], optionsId: ["Raja bijak", "Anaknya yang kecil", "Seekor burung", "Tak seorang pun"], correctIndex: 1 },
      { questionEn: "What did Anansi learn?", questionId: "Apa yang Anansi pelajari?", optionsEn: ["To keep everything", "That wisdom grows by sharing", "To climb faster", "To stay quiet"], optionsId: ["Menyimpan segalanya", "Kebijaksanaan tumbuh dengan berbagi", "Memanjat lebih cepat", "Diam saja"], correctIndex: 1 },
    ],
  },
  {
    slug: "the-fisherman-and-the-golden-fish",
    titleEn: "The Fisherman and the Golden Fish",
    titleId: "Nelayan dan Ikan Emas",
    descriptionEn: "A kind old fisherman frees a magical fish — but when wishes grow greedy, he learns what truly matters.",
    descriptionId: "Nelayan tua yang baik hati membebaskan ikan ajaib — namun ketika permintaan berubah tamak, ia belajar apa yang sungguh berharga.",
    categorySlug: "moral-stories",
    authorSlug: "axto-creative-team",
    coverEmoji: "🐟",
    coverPalette: "ocean",
    ageMin: 4,
    ageMax: 9,
    isPremium: false,
    pages: [
      { illustrationSeed: "gfish-1", textEn: "By the shore of a wide grey sea lived a poor old fisherman and his wife, in a tiny hut with a leaky roof and one old fishing net.", textId: "Di tepi laut kelabu yang luas, tinggallah nelayan tua yang miskin dan istrinya, di gubuk kecil beratap bocor dengan satu jala tua." },
      { illustrationSeed: "gfish-2", textEn: "One morning the fisherman cast his net and pulled up something that shimmered like sunlight — a beautiful golden fish.", textId: "Suatu pagi nelayan menebar jala dan menarik sesuatu yang berkilau seperti cahaya matahari — seekor ikan emas yang indah." },
      { illustrationSeed: "gfish-3", textEn: "To his amazement, the fish spoke. 'Kind fisherman, please let me go, and I will grant you a wish in return.'", textId: "Betapa terkejutnya ia, ikan itu berbicara. 'Nelayan yang baik, tolong lepaskan aku, dan aku akan mengabulkan satu permintaanmu.'" },
      { illustrationSeed: "gfish-4", textEn: "The fisherman had a gentle heart. 'You need no reward, little fish. Go home to your family.' And he slipped the golden fish back into the waves.", textId: "Nelayan itu berhati lembut. 'Kau tak perlu memberi imbalan, ikan kecil. Pulanglah ke keluargamu.' Dan ia melepas ikan emas itu kembali ke ombak." },
      { illustrationSeed: "gfish-5", textEn: "When he told his wife, she frowned. 'You foolish man! Go back and ask for a fine new loaf of bread — ours is stale.'", textId: "Ketika ia bercerita pada istrinya, sang istri mengernyit. 'Suami bodoh! Kembalilah dan minta sepotong roti baru yang enak — roti kita sudah basi.'" },
      { illustrationSeed: "gfish-6", textEn: "The fisherman called the fish, and at once fresh warm bread appeared on their table. But the next day, his wife wanted more.", textId: "Nelayan memanggil ikan itu, dan seketika roti hangat yang segar muncul di meja mereka. Namun keesokan harinya, istrinya ingin lebih." },
      { illustrationSeed: "gfish-7", textEn: "'Ask for a new house!' she said. So he did, and their leaky hut became a snug cottage with a solid roof and a warm fire.", textId: "'Minta rumah baru!' katanya. Maka ia melakukannya, dan gubuk bocor mereka menjadi pondok nyaman beratap kokoh dengan perapian yang hangat." },
      { illustrationSeed: "gfish-8", textEn: "But a cottage was not enough. 'Now ask for a grand mansion, with servants and gardens!' Again the fish granted it. Yet still she was not happy.", textId: "Namun pondok itu tak cukup. 'Sekarang minta rumah megah, dengan pelayan dan taman!' Lagi-lagi ikan itu mengabulkannya. Namun sang istri tetap tak bahagia." },
      { illustrationSeed: "gfish-9", textEn: "'I do not want to be rich,' she declared. 'I want to be Queen of all the land!' The fisherman's heart sank, but he went to the shore once more.", textId: "'Aku tak mau hanya kaya,' katanya. 'Aku ingin menjadi Ratu seluruh negeri!' Hati nelayan itu tenggelam, tetapi ia pergi ke pantai sekali lagi." },
      { illustrationSeed: "gfish-10", textEn: "The sea had turned dark and stormy. The golden fish rose from the churning waves. 'What does she wish for now?' it asked quietly.", textId: "Laut menjadi gelap dan bergolak. Ikan emas muncul dari ombak yang bergemuruh. 'Apa lagi yang ia inginkan sekarang?' tanyanya perlahan." },
      { illustrationSeed: "gfish-11", textEn: "'She wishes to be Queen,' the fisherman whispered, ashamed. The fish looked at him with sad, wise eyes, then vanished beneath the water without a word.", textId: "'Ia ingin menjadi Ratu,' bisik nelayan itu dengan malu. Ikan itu menatapnya dengan mata sedih nan bijak, lalu lenyap di bawah air tanpa sepatah kata." },
      { illustrationSeed: "gfish-12", textEn: "When the fisherman walked home, the mansion was gone. The gardens were gone. There stood only their tiny old hut, with its leaky roof, just as before.", textId: "Ketika nelayan pulang, rumah megah itu lenyap. Tamannya lenyap. Yang tersisa hanya gubuk tua kecil mereka, dengan atap bocornya, persis seperti dulu." },
      { illustrationSeed: "gfish-13", textEn: "His wife sat quietly by the door. For the first time in a long while, she looked at all they still had — each other, a roof, and the wide kind sea.", textId: "Istrinya duduk diam di dekat pintu. Untuk pertama kalinya sejak lama, ia memandang semua yang masih mereka miliki — satu sama lain, sebuah atap, dan laut yang luas dan ramah." },
      { illustrationSeed: "gfish-14", textEn: "'I am sorry,' she said softly. 'I forgot to be thankful.' And from that day they lived simply and gratefully, and were happier than any king or queen. The end.", textId: "'Maafkan aku,' katanya lirih. 'Aku lupa bersyukur.' Dan sejak hari itu mereka hidup sederhana dan penuh syukur, lebih bahagia dari raja atau ratu mana pun. Tamat." },
    ],
    quiz: [
      { questionEn: "Why did the fisherman first let the fish go?", questionId: "Mengapa nelayan mula-mula melepas ikan itu?", optionsEn: ["He wasn't hungry", "He had a kind heart", "The fish was too small", "He was afraid"], optionsId: ["Ia tak lapar", "Ia berhati baik", "Ikannya terlalu kecil", "Ia takut"], correctIndex: 1 },
      { questionEn: "What happened when the wife grew greedy?", questionId: "Apa yang terjadi saat istrinya menjadi tamak?", optionsEn: ["She became Queen", "Everything vanished", "The fish gave more", "Nothing changed"], optionsId: ["Ia jadi Ratu", "Semuanya lenyap", "Ikan memberi lebih", "Tak ada yang berubah"], correctIndex: 1 },
      { questionEn: "What did the wife finally learn?", questionId: "Apa yang akhirnya dipelajari istrinya?", optionsEn: ["To wish for more", "To be thankful", "To catch fish", "To build houses"], optionsId: ["Meminta lebih banyak", "Bersyukur", "Menangkap ikan", "Membangun rumah"], correctIndex: 1 },
    ],
  },
  {
    slug: "the-magic-paintbrush",
    titleEn: "The Magic Paintbrush",
    titleId: "Kuas Ajaib",
    descriptionEn: "A poor but generous boy is given a paintbrush that brings drawings to life — and uses its magic to help everyone but the greedy.",
    descriptionId: "Anak miskin yang murah hati diberi kuas yang menghidupkan gambar — dan memakai keajaibannya untuk menolong semua orang, kecuali yang tamak.",
    categorySlug: "fairy-tales",
    authorSlug: "axto-creative-team",
    coverEmoji: "🖌️",
    coverPalette: "sunrise",
    ageMin: 4,
    ageMax: 9,
    isPremium: false,
    pages: [
      { illustrationSeed: "brush-1", textEn: "In a village in old China lived a poor boy named Ma Liang. He had no paints and no brush, but more than anything in the world, he longed to draw.", textId: "Di sebuah desa di Tiongkok kuno, tinggallah anak miskin bernama Ma Liang. Ia tak punya cat maupun kuas, tetapi lebih dari apa pun di dunia, ia ingin menggambar." },
      { illustrationSeed: "brush-2", textEn: "He practiced with a twig in the sand and a wet finger on stone. Every bird, every fish, every leaf he drew looked almost ready to move.", textId: "Ia berlatih dengan ranting di pasir dan jari basah di atas batu. Setiap burung, ikan, dan daun yang ia gambar tampak nyaris bergerak." },
      { illustrationSeed: "brush-3", textEn: "One night an old man with a kind, glowing face appeared in his dream. 'You have a good and generous heart, Ma Liang. Here is a gift.'", textId: "Suatu malam, seorang kakek berwajah ramah dan bercahaya muncul dalam mimpinya. 'Hatimu baik dan murah hati, Ma Liang. Ini sebuah hadiah.'" },
      { illustrationSeed: "brush-4", textEn: "When Ma Liang woke, a beautiful paintbrush lay in his hand. He dipped it and painted a crane — and the crane flapped its wings and flew off the paper into the sky!", textId: "Ketika Ma Liang bangun, sebuah kuas indah ada di tangannya. Ia mencelupkannya dan melukis burung bangau — dan bangau itu mengepakkan sayap dan terbang dari kertas ke langit!" },
      { illustrationSeed: "brush-5", textEn: "It was a magic paintbrush: whatever he painted came to life. But Ma Liang remembered his empty stomach and his poor neighbours.", textId: "Itu kuas ajaib: apa pun yang ia lukis menjadi hidup. Namun Ma Liang teringat perutnya yang lapar dan tetangganya yang miskin." },
      { illustrationSeed: "brush-6", textEn: "He did not paint gold for himself. Instead he painted a plough for the farmer, a bucket for the water-carrier, and a warm blanket for a shivering old woman.", textId: "Ia tak melukis emas untuk dirinya. Ia justru melukis bajak untuk petani, ember untuk pembawa air, dan selimut hangat untuk nenek yang kedinginan." },
      { illustrationSeed: "brush-7", textEn: "Soon the whole village had what it needed, and everyone loved the kind boy with the magic brush.", textId: "Tak lama, seluruh desa memiliki apa yang mereka butuhkan, dan semua orang menyayangi anak baik dengan kuas ajaib itu." },
      { illustrationSeed: "brush-8", textEn: "But news of the brush reached a greedy rich lord. He sent his guards to seize Ma Liang and lock him in a cold stone room. 'Paint me a mountain of gold!' he demanded.", textId: "Namun kabar tentang kuas itu sampai ke telinga tuan tanah yang tamak. Ia mengirim pengawal menangkap Ma Liang dan menguncinya di ruang batu yang dingin. 'Lukiskan aku gunung emas!' perintahnya." },
      { illustrationSeed: "brush-9", textEn: "Ma Liang thought carefully. He agreed — but he was clever. First he painted a wide blue sea. 'Where is my gold?' snapped the lord.", textId: "Ma Liang berpikir hati-hati. Ia setuju — tetapi ia cerdik. Pertama ia melukis laut biru yang luas. 'Mana emasku?' bentak sang tuan tanah." },
      { illustrationSeed: "brush-10", textEn: "'The gold is on an island across the water,' said Ma Liang, and he painted a fine ship. The greedy lord and his guards jumped aboard at once.", textId: "'Emasnya ada di pulau seberang,' kata Ma Liang, lalu ia melukis kapal yang bagus. Tuan tanah tamak dan pengawalnya langsung melompat naik." },
      { illustrationSeed: "brush-11", textEn: "'Faster! Faster!' cried the lord. So Ma Liang painted a strong wind. He painted it stronger, and stronger — until the waves rose and carried the ship far, far over the horizon.", textId: "'Lebih cepat! Lebih cepat!' teriak sang tuan tanah. Maka Ma Liang melukis angin kencang. Ia melukisnya makin kencang, makin kencang — hingga ombak meninggi dan membawa kapal itu jauh, jauh melewati cakrawala." },
      { illustrationSeed: "brush-12", textEn: "The greedy lord was never seen troubling the village again. Ma Liang returned home free, and to the people who were kind and worked hard.", textId: "Tuan tanah tamak itu tak pernah lagi terlihat mengganggu desa. Ma Liang pulang dengan bebas, kembali kepada orang-orang yang baik dan pekerja keras." },
      { illustrationSeed: "brush-13", textEn: "For the rest of his days, Ma Liang used his magic brush only to help those in need — for he knew that a gift is truest when it is shared. The end.", textId: "Sepanjang sisa hidupnya, Ma Liang memakai kuas ajaibnya hanya untuk menolong yang membutuhkan — sebab ia tahu bahwa sebuah anugerah paling berarti ketika dibagikan. Tamat." },
    ],
    quiz: [
      { questionEn: "What did the magic paintbrush do?", questionId: "Apa yang dilakukan kuas ajaib itu?", optionsEn: ["Made things invisible", "Brought drawings to life", "Turned things to gold", "Told stories"], optionsId: ["Membuat benda tak terlihat", "Menghidupkan gambar", "Mengubah benda jadi emas", "Bercerita"], correctIndex: 1 },
      { questionEn: "What did Ma Liang paint for the village?", questionId: "Apa yang Ma Liang lukis untuk desa?", optionsEn: ["Gold for himself", "Tools and blankets to help others", "A castle", "Nothing"], optionsId: ["Emas untuk dirinya", "Alat dan selimut untuk menolong", "Sebuah istana", "Tidak ada"], correctIndex: 1 },
      { questionEn: "How did Ma Liang outwit the greedy lord?", questionId: "Bagaimana Ma Liang mengecoh tuan tanah tamak?", optionsEn: ["He gave him gold", "He painted a storm at sea", "He ran away", "He apologised"], optionsId: ["Memberinya emas", "Melukis badai di laut", "Melarikan diri", "Meminta maaf"], correctIndex: 1 },
    ],
  },
  {
    slug: "stone-soup",
    titleEn: "Stone Soup",
    titleId: "Sup Batu",
    descriptionEn: "Three tired travellers arrive at a village with nothing but a stone — and teach everyone the magic of sharing.",
    descriptionId: "Tiga pengembara lelah tiba di desa hanya dengan sebuah batu — dan mengajarkan semua orang keajaiban berbagi.",
    categorySlug: "friendship",
    authorSlug: "axto-creative-team",
    coverEmoji: "🍲",
    coverPalette: "forest",
    ageMin: 3,
    ageMax: 8,
    isPremium: false,
    pages: [
      { illustrationSeed: "soup-1", textEn: "Three tired travellers walked a long dusty road until they reached a small village at dusk. They were hungry, and they had no food at all.", textId: "Tiga pengembara yang lelah menyusuri jalan berdebu yang panjang hingga tiba di desa kecil saat senja. Mereka lapar, dan sama sekali tak punya makanan." },
      { illustrationSeed: "soup-2", textEn: "They knocked on doors, but times were hard. 'We have nothing to spare,' said each villager, and quietly closed the door.", textId: "Mereka mengetuk pintu-pintu, tetapi masa itu sulit. 'Kami tak punya lebih,' kata setiap warga, lalu menutup pintu perlahan." },
      { illustrationSeed: "soup-3", textEn: "The travellers were not angry. Instead, they smiled. 'Then we shall make Stone Soup, and share it with the whole village!'", textId: "Para pengembara tidak marah. Mereka justru tersenyum. 'Kalau begitu kami akan membuat Sup Batu, dan membaginya dengan seluruh desa!'" },
      { illustrationSeed: "soup-4", textEn: "In the village square they lit a fire, set a big black pot of water to boil, and gently placed one smooth grey stone inside.", textId: "Di alun-alun desa mereka menyalakan api, menjerang periuk hitam besar berisi air, dan meletakkan sebuah batu kelabu yang halus ke dalamnya." },
      { illustrationSeed: "soup-5", textEn: "Curious villagers gathered round. 'Stone soup?' 'Oh yes,' said a traveller, stirring. 'It is delicious — though a pinch of salt would make it even better.'", textId: "Warga yang penasaran berkumpul. 'Sup batu?' 'Oh ya,' kata seorang pengembara sambil mengaduk. 'Rasanya lezat — meski sejumput garam akan membuatnya lebih enak lagi.'" },
      { illustrationSeed: "soup-6", textEn: "'I have salt!' said a woman, and hurried to fetch some. Soon a man said, 'I have a few carrots in my cellar,' and in they went.", textId: "'Aku punya garam!' kata seorang perempuan, lalu bergegas mengambilnya. Tak lama seorang lelaki berkata, 'Aku punya beberapa wortel di gudang,' dan wortel pun dimasukkan." },
      { illustrationSeed: "soup-7", textEn: "'Onions would help,' said a traveller kindly. 'I have onions!' called a boy. Then came potatoes, then barley, then a handful of fresh green herbs.", textId: "'Bawang akan menambah rasa,' kata pengembara dengan ramah. 'Aku punya bawang!' seru seorang anak. Lalu datang kentang, jelai, dan segenggam rempah hijau segar." },
      { illustrationSeed: "soup-8", textEn: "One by one, each villager brought a little of what they had — a cabbage, some beans, a bit of milk — and stirred it into the bubbling pot.", textId: "Satu per satu, tiap warga membawa sedikit yang mereka punya — sebutir kubis, sedikit kacang, seteguk susu — dan mengaduknya ke dalam periuk yang mendidih." },
      { illustrationSeed: "soup-9", textEn: "The smell that rose from the pot was wonderful. Something that had begun with a single stone was becoming a feast for everyone.", textId: "Aroma yang naik dari periuk itu sungguh menggoda. Sesuatu yang bermula dari sebutir batu kini menjadi jamuan untuk semua orang." },
      { illustrationSeed: "soup-10", textEn: "When the soup was ready, the whole village sat together in the square, sharing bowls, bread, and laughter under the first stars.", textId: "Ketika sup matang, seluruh desa duduk bersama di alun-alun, berbagi mangkuk, roti, dan tawa di bawah bintang-bintang pertama." },
      { illustrationSeed: "soup-11", textEn: "'What magic stone makes such a soup?' the villagers asked. The travellers smiled. 'The stone is just a stone. The magic was you — sharing what you had.'", textId: "'Batu ajaib apa yang membuat sup seperti ini?' tanya warga. Para pengembara tersenyum. 'Batu itu hanyalah batu. Keajaibannya adalah kalian — berbagi apa yang kalian punya.'" },
      { illustrationSeed: "soup-12", textEn: "The next morning the travellers walked on, leaving behind a village that had learned the sweetest recipe of all: that a little from everyone becomes plenty for all. The end.", textId: "Keesokan paginya para pengembara melanjutkan perjalanan, meninggalkan desa yang telah belajar resep termanis: bahwa sedikit dari setiap orang menjadi berlimpah untuk semua. Tamat." },
    ],
    quiz: [
      { questionEn: "What did the travellers put in the pot first?", questionId: "Apa yang pertama dimasukkan pengembara ke periuk?", optionsEn: ["A carrot", "A stone", "An onion", "Salt"], optionsId: ["Wortel", "Sebuah batu", "Bawang", "Garam"], correctIndex: 1 },
      { questionEn: "How did the soup become a feast?", questionId: "Bagaimana sup itu menjadi jamuan besar?", optionsEn: ["By magic", "Everyone shared a little food", "The stone grew", "They bought it"], optionsId: ["Dengan sihir", "Semua berbagi sedikit makanan", "Batunya membesar", "Mereka membelinya"], correctIndex: 1 },
      { questionEn: "What was the real 'magic'?", questionId: "Apa 'keajaiban' yang sebenarnya?", optionsEn: ["The stone", "Sharing together", "The big pot", "The fire"], optionsId: ["Batunya", "Berbagi bersama", "Periuk besar", "Apinya"], correctIndex: 1 },
    ],
  },
  {
    slug: "the-clever-rabbit-and-the-lion",
    titleEn: "The Clever Rabbit and the Lion",
    titleId: "Kelinci Cerdik dan Singa",
    descriptionEn: "From the ancient Panchatantra of India: a small rabbit uses a big idea to save the whole forest from a greedy lion.",
    descriptionId: "Dari Panchatantra kuno India: kelinci kecil memakai ide besar untuk menyelamatkan seluruh hutan dari singa yang serakah.",
    categorySlug: "moral-stories",
    authorSlug: "axto-creative-team",
    coverEmoji: "🐇",
    coverPalette: "meadow",
    ageMin: 4,
    ageMax: 9,
    isPremium: false,
    pages: [
      { illustrationSeed: "rabbit-lion-1", textEn: "Long ago, in a deep green forest in India, there lived a lion who was never, ever satisfied. Every day he hunted more than he could eat, and the animals of the forest lived in fear.", textId: "Dahulu kala, di hutan hijau nan lebat di India, hiduplah seekor singa yang tak pernah puas. Setiap hari ia berburu lebih dari yang bisa ia makan, dan hewan-hewan hutan hidup dalam ketakutan." },
      { illustrationSeed: "rabbit-lion-2", textEn: "At last the animals gathered under the great banyan tree. 'If this goes on,' said the old elephant, 'soon there will be no one left in the forest at all.'", textId: "Akhirnya hewan-hewan berkumpul di bawah pohon beringin besar. 'Kalau begini terus,' kata gajah tua, 'sebentar lagi tak akan ada yang tersisa di hutan ini.'" },
      { illustrationSeed: "rabbit-lion-3", textEn: "So they made a brave bargain with the lion: every day, one animal would come to him by lot, and in return he would leave all the others in peace. The lion licked his lips and agreed.", textId: "Maka mereka membuat kesepakatan berani dengan singa: setiap hari, satu hewan akan datang kepadanya berdasarkan undian, dan sebagai gantinya ia membiarkan yang lain hidup tenang. Singa menjilat bibirnya dan setuju." },
      { illustrationSeed: "rabbit-lion-4", textEn: "One morning, the lot fell to a small grey rabbit. The other animals hung their heads. 'Poor little one,' they whispered. But the rabbit's bright eyes were already thinking.", textId: "Suatu pagi, undian jatuh pada seekor kelinci kecil abu-abu. Hewan-hewan lain menunduk sedih. 'Kasihan si kecil,' bisik mereka. Namun mata cerah kelinci itu sudah mulai berpikir." },
      { illustrationSeed: "rabbit-lion-5", textEn: "The rabbit did not hurry. He hopped slowly through the forest, stopped to nibble sweet grass, and arrived at the lion's den when the sun was already high and hot.", textId: "Kelinci itu tidak terburu-buru. Ia melompat pelan menembus hutan, berhenti mengunyah rumput manis, dan tiba di sarang singa saat matahari sudah tinggi dan panas." },
      { illustrationSeed: "rabbit-lion-6", textEn: "The lion was pacing and roaring with hunger. 'You are LATE, and you are SMALL!' he thundered. 'Is this how the forest keeps its promise?'", textId: "Singa mondar-mandir dan mengaum kelaparan. 'Kau TERLAMBAT, dan kau KECIL!' geramnya. 'Beginikah cara hutan menepati janjinya?'" },
      { illustrationSeed: "rabbit-lion-7", textEn: "The rabbit bowed very low. 'Forgive me, Your Majesty. Five rabbits were sent to you this morning — but on the way, another lion leapt out and ate the other four!'", textId: "Kelinci membungkuk dalam-dalam. 'Ampuni hamba, Baginda. Lima kelinci dikirim untukmu pagi ini — tetapi di tengah jalan, singa lain melompat keluar dan memakan empat lainnya!'" },
      { illustrationSeed: "rabbit-lion-8", textEn: "'ANOTHER lion? In MY forest?' The lion's mane bristled like a storm cloud. 'Where is this thief? Take me to him at once!'", textId: "'Singa LAIN? Di hutan-KU?' Surai singa berdiri bagai awan badai. 'Di mana pencuri itu? Antarkan aku kepadanya sekarang juga!'" },
      { illustrationSeed: "rabbit-lion-9", textEn: "The clever rabbit led him down a winding path to an old stone well, deep and still and full of clear water. 'He lives down there, Your Majesty,' whispered the rabbit.", textId: "Kelinci cerdik menuntunnya melewati jalan berliku menuju sumur batu tua, dalam, tenang, dan penuh air jernih. 'Ia tinggal di bawah sana, Baginda,' bisik kelinci." },
      { illustrationSeed: "rabbit-lion-10", textEn: "The lion looked over the edge — and there, in the water, glared a mighty lion with a great dark mane, staring straight back at him!", textId: "Singa menjenguk ke tepi sumur — dan di sana, di dalam air, seekor singa perkasa bersurai gelap menatapnya tajam!" },
      { illustrationSeed: "rabbit-lion-11", textEn: "'THIEF!' roared the lion, and the well roared back. That was too much. He leapt at his rival with all his strength — and splashed into the deep, deep water.", textId: "'PENCURI!' aum sang singa, dan sumur itu mengaum balik. Itu keterlaluan baginya. Ia melompat menerkam lawannya sekuat tenaga — dan tercebur ke air yang dalam." },
      { illustrationSeed: "rabbit-lion-12", textEn: "The lion splashed and spluttered and finally dragged himself out, soaked and shivering and very much smaller-feeling. Without a word, he slunk away from the forest and never returned.", textId: "Singa itu megap-megap dan akhirnya merangkak keluar, basah kuyup, menggigil, dan merasa jauh lebih kecil. Tanpa sepatah kata pun, ia pergi meninggalkan hutan dan tak pernah kembali." },
      { illustrationSeed: "rabbit-lion-13", textEn: "The animals danced under the banyan tree and lifted the little rabbit onto the elephant's back. 'The smallest of us saved us all!' they cheered.", textId: "Hewan-hewan menari di bawah pohon beringin dan mengangkat kelinci kecil ke punggung gajah. 'Yang terkecil di antara kita menyelamatkan kita semua!' sorak mereka." },
      { illustrationSeed: "rabbit-lion-14", textEn: "For strength wins many fights, says the old Panchatantra — but wisdom wins the ones that matter. The end.", textId: "Sebab kekuatan memenangkan banyak pertarungan, kata Panchatantra tua — tetapi kecerdikan memenangkan pertarungan yang paling penting. Tamat." },
    ],
    quiz: [
      { questionEn: "Why were the forest animals afraid?", questionId: "Mengapa hewan-hewan hutan ketakutan?", optionsEn: ["A storm was coming", "The lion hunted too much", "The well was empty", "The elephant was angry"], optionsId: ["Badai akan datang", "Singa berburu terlalu banyak", "Sumur kering", "Gajah sedang marah"], correctIndex: 1 },
      { questionEn: "What did the rabbit show the lion in the well?", questionId: "Apa yang ditunjukkan kelinci kepada singa di sumur?", optionsEn: ["A fish", "A treasure", "His own reflection", "Another rabbit"], optionsId: ["Seekor ikan", "Harta karun", "Bayangannya sendiri", "Kelinci lain"], correctIndex: 2 },
      { questionEn: "What does the story teach?", questionId: "Apa pesan cerita ini?", optionsEn: ["Bigger is stronger", "Wisdom can beat strength", "Never be late", "Lions are bad"], optionsId: ["Besar berarti kuat", "Kecerdikan bisa mengalahkan kekuatan", "Jangan pernah terlambat", "Singa itu jahat"], correctIndex: 1 },
    ],
  },
  {
    slug: "timun-mas-and-the-giant",
    titleEn: "Timun Mas and the Giant",
    titleId: "Timun Mas dan Raksasa",
    descriptionEn: "A beloved Indonesian legend: a girl born from a golden cucumber outruns a giant with four small magical gifts and her own great courage.",
    descriptionId: "Legenda Indonesia yang dicintai: gadis yang lahir dari timun emas mengalahkan raksasa dengan empat bingkisan ajaib dan keberaniannya sendiri.",
    categorySlug: "adventure",
    authorSlug: "axto-creative-team",
    coverEmoji: "🥒",
    coverPalette: "meadow",
    ageMin: 4,
    ageMax: 10,
    isPremium: false,
    pages: [
      { illustrationSeed: "timun-1", textEn: "On the green slopes of a Javanese mountain lived a widow named Mbok Srini, who wished for a child more than for anything under the sky.", textId: "Di lereng hijau sebuah gunung di Jawa, hiduplah seorang janda bernama Mbok Srini, yang menginginkan seorang anak melebihi apa pun di kolong langit." },
      { illustrationSeed: "timun-2", textEn: "One night a giant came striding over the hills, tall as a coconut tree, with a laugh like falling rocks. 'Plant this seed, little woman,' he rumbled, 'and you shall have your child. But when she turns seventeen, she is MINE.'", textId: "Suatu malam, seorang raksasa datang melangkahi bukit-bukit, tinggi bagai pohon kelapa, dengan tawa seperti batu runtuh. 'Tanamlah biji ini, wahai ibu,' gemuruhnya, 'dan kau akan mendapat anak. Tapi saat ia berusia tujuh belas tahun, ia MILIKKU.'" },
      { illustrationSeed: "timun-3", textEn: "Frightened but longing, Mbok Srini planted the seed. It grew into a vine, and on the vine swelled one enormous golden cucumber that glowed like the morning sun.", textId: "Takut namun penuh harap, Mbok Srini menanam biji itu. Tumbuhlah sulur menjalar, dan pada sulur itu membesar sebuah timun emas raksasa yang berkilau bagai matahari pagi." },
      { illustrationSeed: "timun-4", textEn: "When she split it open, inside lay a baby girl with cheeks like rose petals. Mbok Srini named her Timun Mas — Golden Cucumber — and loved her more each day.", textId: "Ketika dibelahnya, di dalamnya terbaring bayi perempuan berpipi bagai kelopak mawar. Mbok Srini menamainya Timun Mas — Timun Emas — dan menyayanginya lebih setiap hari." },
      { illustrationSeed: "timun-5", textEn: "The years flew like birds. Timun Mas grew clever and kind and quick as a mountain stream. But the night before her seventeenth birthday, the ground began to shake.", textId: "Tahun-tahun berlalu bagai burung terbang. Timun Mas tumbuh cerdas, baik hati, dan gesit bagai aliran sungai gunung. Namun malam sebelum ulang tahunnya yang ketujuh belas, tanah mulai berguncang." },
      { illustrationSeed: "timun-6", textEn: "'Run, my child!' cried Mbok Srini, pressing a small cloth bundle into her hands. 'A wise hermit gave me these four gifts long ago. Use them when all seems lost!'", textId: "'Larilah, anakku!' seru Mbok Srini sambil menyelipkan buntelan kain kecil ke tangannya. 'Seorang pertapa bijak memberiku empat bingkisan ini dulu. Gunakan saat semua terasa hilang!'" },
      { illustrationSeed: "timun-7", textEn: "Timun Mas ran through the moonlit forest, and the giant's footsteps boomed behind her like thunder. Closer... closer... She opened the bundle and threw the first gift: a handful of cucumber seeds.", textId: "Timun Mas berlari menembus hutan bermandi cahaya bulan, dan langkah raksasa menggelegar di belakangnya bagai guntur. Makin dekat... makin dekat... Ia membuka buntelan dan melempar bingkisan pertama: segenggam biji timun." },
      { illustrationSeed: "timun-8", textEn: "Instantly a tangle of vines burst from the earth, thick with heavy golden cucumbers. The greedy giant stopped to gobble them up — and Timun Mas flew ahead.", textId: "Seketika sulur-sulur menyembur dari tanah, lebat dengan timun emas yang berat. Raksasa yang rakus berhenti untuk melahapnya — dan Timun Mas melesat jauh ke depan." },
      { illustrationSeed: "timun-9", textEn: "But soon the thunder-steps returned. She threw the second gift: needles. They sprang up into a forest of bamboo, sharp as spears. The giant crashed through, roaring, scratched from head to toe.", textId: "Namun tak lama, langkah guntur itu kembali. Ia melempar bingkisan kedua: jarum-jarum. Semuanya menjelma hutan bambu runcing bagai tombak. Raksasa menerobos sambil mengaum, tergores dari kepala sampai kaki." },
      { illustrationSeed: "timun-10", textEn: "The third gift was a handful of salt. It became a wide rolling sea! The giant waded in, gasping and swallowing waves, but still he came on.", textId: "Bingkisan ketiga adalah segenggam garam. Garam itu menjelma lautan luas bergelombang! Raksasa menyeberang, megap-megap menelan ombak, tapi ia terus mengejar." },
      { illustrationSeed: "timun-11", textEn: "At last, with trembling fingers, Timun Mas threw the final gift: a paste of hot shrimp sauce. Where it landed, the earth bubbled into a lake of boiling mud, and the giant sank down, down, down — and was gone.", textId: "Akhirnya, dengan jari gemetar, Timun Mas melempar bingkisan terakhir: terasi. Di tempat jatuhnya, bumi menggelegak menjadi danau lumpur mendidih, dan raksasa itu tenggelam, tenggelam, tenggelam — lalu lenyap." },
      { illustrationSeed: "timun-12", textEn: "The forest fell silent. The moon came out from behind the clouds. Timun Mas walked home on shaking legs, and her mother ran to meet her with tears of joy.", textId: "Hutan menjadi sunyi. Bulan muncul dari balik awan. Timun Mas berjalan pulang dengan kaki gemetar, dan ibunya berlari menyambut dengan air mata bahagia." },
      { illustrationSeed: "timun-13", textEn: "From that day, mother and daughter lived in peace on their green mountainside, and no giant ever troubled the valley again.", textId: "Sejak hari itu, ibu dan anak hidup damai di lereng gunung yang hijau, dan tak ada raksasa yang mengganggu lembah itu lagi." },
      { illustrationSeed: "timun-14", textEn: "For courage is not being unafraid, says the old tale — it is running on even when your legs tremble, and using every gift you are given. The end.", textId: "Sebab keberanian bukan berarti tak takut, kata dongeng lama — melainkan terus berlari meski kakimu gemetar, dan menggunakan setiap bekal yang kau miliki. Tamat." },
    ],
    quiz: [
      { questionEn: "Where was baby Timun Mas found?", questionId: "Di mana bayi Timun Mas ditemukan?", optionsEn: ["In a basket", "Inside a golden cucumber", "Under a tree", "By the river"], optionsId: ["Di dalam keranjang", "Di dalam timun emas", "Di bawah pohon", "Di tepi sungai"], correctIndex: 1 },
      { questionEn: "Which gift finally stopped the giant?", questionId: "Bingkisan mana yang akhirnya menghentikan raksasa?", optionsEn: ["Cucumber seeds", "Needles", "Salt", "Shrimp paste"], optionsId: ["Biji timun", "Jarum", "Garam", "Terasi"], correctIndex: 3 },
      { questionEn: "What does the story say courage is?", questionId: "Menurut cerita, apa itu keberanian?", optionsEn: ["Never feeling afraid", "Running on even when afraid", "Being the biggest", "Hiding well"], optionsId: ["Tak pernah takut", "Terus berlari meski takut", "Menjadi yang terbesar", "Pandai bersembunyi"], correctIndex: 1 },
    ],
  },
  {
    slug: "the-ugly-duckling",
    titleEn: "The Ugly Duckling",
    titleId: "Itik Buruk Rupa",
    descriptionEn: "Hans Christian Andersen's gentle classic: a little bird who never fit in discovers, after a long hard year, exactly who he was born to be.",
    descriptionId: "Klasik lembut Hans Christian Andersen: seekor anak unggas yang tak pernah diterima akhirnya menemukan, setelah setahun yang berat, siapa dirinya sebenarnya.",
    categorySlug: "emotions",
    authorSlug: "axto-creative-team",
    coverEmoji: "🦢",
    coverPalette: "sky",
    ageMin: 3,
    ageMax: 8,
    isPremium: false,
    pages: [
      { illustrationSeed: "duckling-1", textEn: "By a quiet pond on a summer farm, a mother duck sat on her nest, waiting. One by one the eggs cracked open — peep! peep! — until only the biggest egg was left.", textId: "Di tepi kolam yang tenang di sebuah ladang musim panas, induk bebek duduk mengerami telurnya, menunggu. Satu per satu telur menetas — piyik! piyik! — hingga tersisa telur yang paling besar." },
      { illustrationSeed: "duckling-2", textEn: "At last it split, and out tumbled a chick — big, grey, and clumsy. 'Well,' said the mother duck, 'you don't look like the others. But you are mine, and I love you.'", textId: "Akhirnya telur itu terbelah, dan keluarlah seekor anak unggas — besar, abu-abu, dan canggung. 'Hmm,' kata induk bebek, 'kau tak mirip yang lain. Tapi kau anakku, dan aku menyayangimu.'" },
      { illustrationSeed: "duckling-3", textEn: "But the farmyard was not kind. The hens pecked him, the turkey puffed at him, and even his brothers and sisters quacked, 'Go away, ugly duckling!'", textId: "Namun penghuni ladang tidaklah ramah. Ayam-ayam mematuknya, kalkun menggembungkan bulunya, bahkan saudara-saudaranya berkwek, 'Pergilah, itik buruk rupa!'" },
      { illustrationSeed: "duckling-4", textEn: "One grey evening, his heart heavier than his little wings, the duckling slipped under the fence and wandered away alone.", textId: "Suatu senja kelabu, dengan hati yang lebih berat daripada sayap kecilnya, itik itu menyelinap di bawah pagar dan mengembara sendirian." },
      { illustrationSeed: "duckling-5", textEn: "Autumn came with cold rain. The duckling hid among the reeds of a marsh, where wild ducks laughed at his strange looks but let him stay.", textId: "Musim gugur datang membawa hujan dingin. Itik itu bersembunyi di antara gelagah rawa, tempat bebek-bebek liar menertawakan rupanya yang aneh namun membiarkannya tinggal." },
      { illustrationSeed: "duckling-6", textEn: "One evening a flock of great white birds flew overhead, their long necks stretched toward the south, their wings singing in the wind. The duckling did not know their name — but his heart ached to follow them.", textId: "Suatu senja, sekawanan burung putih besar terbang di atasnya, leher panjang mereka terjulur ke selatan, sayap mereka berdesir di angin. Itik itu tak tahu nama mereka — namun hatinya nyeri ingin ikut." },
      { illustrationSeed: "duckling-7", textEn: "Winter was long and bitter. The duckling nearly froze in the pond ice, and a kind farmer carried him home — but he knocked over the milk pail in fright, and had to flee again.", textId: "Musim dingin panjang dan menggigit. Itik itu nyaris membeku di es kolam, dan seorang petani baik hati membawanya pulang — namun karena ketakutan ia menumpahkan ember susu, dan harus lari lagi." },
      { illustrationSeed: "duckling-8", textEn: "Somehow, through frost and hunger and loneliness, the little bird survived until the willows turned green and the air smelled of spring.", textId: "Entah bagaimana, melewati embun beku, lapar, dan sepi, unggas kecil itu bertahan hingga pohon willow menghijau dan udara berbau musim semi." },
      { illustrationSeed: "duckling-9", textEn: "He spread his wings — and they were strong now, wide and white, and they carried him high over the gardens to a shining lake where three great white birds glided like ships.", textId: "Ia mengembangkan sayapnya — kini kuat, lebar, dan putih, membawanya tinggi melintasi taman menuju danau berkilau tempat tiga burung putih besar meluncur bagai kapal." },
      { illustrationSeed: "duckling-10", textEn: "'They will chase me away, like everyone else,' he thought sadly. 'But better to be chased by such beautiful birds than pecked by hens.' And he flew down to meet them.", textId: "'Mereka pasti akan mengusirku, seperti yang lain,' pikirnya sedih. 'Tapi lebih baik diusir burung-burung seindah itu daripada dipatuki ayam.' Lalu ia turun menghampiri mereka." },
      { illustrationSeed: "duckling-11", textEn: "He bowed his head, waiting for the pecks — and saw, in the still water, his own reflection: not a clumsy grey duckling at all, but a swan, white as snow, graceful as morning.", textId: "Ia menundukkan kepala, siap dipatuk — dan melihat, di air yang tenang, bayangannya sendiri: sama sekali bukan itik abu-abu yang canggung, melainkan seekor angsa, putih bagai salju, anggun bagai pagi." },
      { illustrationSeed: "duckling-12", textEn: "The great swans swam around him and stroked him with their beaks. Children on the shore clapped and cried, 'The new one is the most beautiful of all!'", textId: "Angsa-angsa besar berenang mengelilinginya dan membelainya dengan paruh mereka. Anak-anak di tepi danau bertepuk tangan dan berseru, 'Yang baru itu paling indah dari semuanya!'" },
      { illustrationSeed: "duckling-13", textEn: "And the young swan felt shy and hid his head under his wing — for a heart that has known sorrow is never proud. He was happy, deeply happy, but not proud.", textId: "Angsa muda itu tersipu dan menyembunyikan kepala di bawah sayapnya — sebab hati yang pernah mengenal duka tak pernah menjadi sombong. Ia bahagia, sungguh bahagia, tapi tidak sombong." },
      { illustrationSeed: "duckling-14", textEn: "It does not matter, said Andersen, if you are born in a duckyard — so long as you are hatched from a swan's egg. You are becoming who you truly are. The end.", textId: "Tak masalah, kata Andersen, jika kau lahir di kandang bebek — selama kau menetas dari telur angsa. Kau sedang tumbuh menjadi dirimu yang sebenarnya. Tamat." },
    ],
    quiz: [
      { questionEn: "Why did the duckling leave the farmyard?", questionId: "Mengapa itik itu meninggalkan ladang?", optionsEn: ["He wanted adventure", "Everyone was unkind to him", "He was hungry", "The pond froze"], optionsId: ["Ia ingin bertualang", "Semua bersikap tak baik padanya", "Ia lapar", "Kolam membeku"], correctIndex: 1 },
      { questionEn: "What did he see in the water in spring?", questionId: "Apa yang dilihatnya di air saat musim semi?", optionsEn: ["A fish", "A boat", "His reflection — a swan", "Another duckling"], optionsId: ["Seekor ikan", "Sebuah perahu", "Bayangannya — seekor angsa", "Itik lain"], correctIndex: 2 },
      { questionEn: "How did the swan behave when praised?", questionId: "Bagaimana sikap angsa saat dipuji?", optionsEn: ["Proud and loud", "Happy but humble", "Angry", "He flew away"], optionsId: ["Sombong dan berisik", "Bahagia tapi rendah hati", "Marah", "Ia terbang pergi"], correctIndex: 1 },
    ],
  },
  {
    slug: "the-bremen-town-musicians",
    titleEn: "The Bremen Town Musicians",
    titleId: "Para Pemusik Kota Bremen",
    descriptionEn: "The Brothers Grimm classic: four old animals nobody wanted team up, scare off a band of robbers, and find a home — together.",
    descriptionId: "Klasik Grimm bersaudara: empat hewan tua yang tak diinginkan bersatu, mengusir kawanan perampok, dan menemukan rumah — bersama-sama.",
    categorySlug: "friendship",
    authorSlug: "axto-creative-team",
    coverEmoji: "🎺",
    coverPalette: "sunset",
    ageMin: 4,
    ageMax: 9,
    isPremium: false,
    pages: [
      { illustrationSeed: "bremen-1", textEn: "There was once a donkey who had carried sacks to the mill for many long years. When he grew too old to work, his master decided to send him away — so the donkey set off down the road to Bremen. 'I shall be a town musician,' he said.", textId: "Alkisah seekor keledai telah bertahun-tahun memikul karung ke penggilingan. Ketika ia terlalu tua untuk bekerja, tuannya hendak membuangnya — maka keledai itu berangkat menyusuri jalan ke Bremen. 'Aku akan menjadi pemusik kota,' katanya." },
      { illustrationSeed: "bremen-2", textEn: "On the road he found an old hunting dog lying in the grass, panting sadly. 'I am too slow to hunt now, and my master has no use for me.' 'Come to Bremen!' said the donkey. 'You shall play the drum.'", textId: "Di jalan ia menemukan seekor anjing pemburu tua terbaring di rumput, terengah sedih. 'Aku terlalu lambat untuk berburu sekarang, dan tuanku tak membutuhkanku lagi.' 'Ikutlah ke Bremen!' kata keledai. 'Kau akan menabuh genderang.'" },
      { illustrationSeed: "bremen-3", textEn: "Soon they met a cat sitting by the road with a face like three days of rain. 'I am old, my teeth are dull, and I would rather sit by the stove than chase mice — so no one wants me.' 'Join us! You shall sing soprano.'", textId: "Tak lama mereka bertemu seekor kucing duduk di tepi jalan dengan wajah bagai hujan tiga hari. 'Aku tua, gigiku tumpul, dan aku lebih suka duduk dekat tungku daripada mengejar tikus — jadi tak ada yang menginginkanku.' 'Bergabunglah! Kau akan menyanyi sopran.'" },
      { illustrationSeed: "bremen-4", textEn: "At a farmyard gate, a rooster was crowing with all his might. 'Guests are coming on Sunday,' he wailed, 'and the cook means to put me in the soup! I crow while I still can.' 'Come with us to Bremen — anything is better than the soup!'", textId: "Di gerbang sebuah ladang, seekor ayam jantan berkokok sekuat tenaga. 'Tamu akan datang hari Minggu,' ratapnya, 'dan juru masak hendak memasukkanku ke dalam sup! Aku berkokok selagi bisa.' 'Ikutlah kami ke Bremen — apa pun lebih baik daripada sup!'" },
      { illustrationSeed: "bremen-5", textEn: "Night fell before they reached the city, and deep in the forest they saw a light. Through the window of a little house they spied a table heaped with food and drink — and around it, a band of robbers counting stolen gold.", textId: "Malam tiba sebelum mereka sampai di kota, dan jauh di dalam hutan mereka melihat cahaya. Lewat jendela sebuah rumah kecil mereka mengintip meja penuh makanan dan minuman — dan di sekelilingnya, kawanan perampok tengah menghitung emas curian." },
      { illustrationSeed: "bremen-6", textEn: "The four friends put their heads together and made a plan. The donkey stood at the window, the dog climbed on his back, the cat on the dog, and the rooster perched on top of them all.", textId: "Keempat sahabat itu berunding dan menyusun rencana. Keledai berdiri di dekat jendela, anjing naik ke punggungnya, kucing naik ke atas anjing, dan ayam jantan bertengger paling atas." },
      { illustrationSeed: "bremen-7", textEn: "Then, at a signal, they made their music all at once: the donkey brayed, the dog barked, the cat yowled, and the rooster crowed — and they crashed through the window in a shower of glass!", textId: "Lalu, pada satu aba-aba, mereka bermusik serentak: keledai meringkik, anjing menggonggong, kucing mengeong keras, dan ayam berkokok — dan mereka menerjang jendela hingga kaca berhamburan!" },
      { illustrationSeed: "bremen-8", textEn: "The robbers leapt up in terror. 'A ghost! A monster! A judge with a sword!' they cried, falling over each other as they fled into the dark forest.", textId: "Para perampok melompat ketakutan. 'Hantu! Monster! Hakim bersama pedang!' teriak mereka, jatuh bertumpukan sambil lari ke hutan gelap." },
      { illustrationSeed: "bremen-9", textEn: "The four musicians sat down at the table and ate as if they had been hungry for a month — which, in truth, they had. Then each found a sleeping place to his liking, and the lights went out.", textId: "Keempat pemusik duduk di meja dan makan seolah sudah lapar sebulan — dan memang begitulah adanya. Lalu masing-masing mencari tempat tidur kesukaannya, dan lampu pun padam." },
      { illustrationSeed: "bremen-10", textEn: "At midnight, the bravest robber crept back to the dark house. In the kitchen, the cat's eyes glowed — he took them for burning coals, and reached out to light a match.", textId: "Tengah malam, perampok yang paling berani menyelinap kembali ke rumah gelap itu. Di dapur, mata kucing berpendar — dikiranya bara api, dan ia mengulurkan tangan hendak menyalakan korek." },
      { illustrationSeed: "bremen-11", textEn: "The cat flew at his face, spitting and scratching. He stumbled to the door — the dog bit his leg. He staggered through the yard — the donkey kicked him high over the fence. And from the roof the rooster screamed, 'Cock-a-doodle-doo!'", textId: "Kucing menerkam wajahnya, mendesis dan mencakar. Ia terhuyung ke pintu — anjing menggigit kakinya. Ia sempoyongan melewati halaman — keledai menendangnya tinggi melewati pagar. Dan dari atap ayam jantan berteriak, 'Kukuruyuk!'" },
      { illustrationSeed: "bremen-12", textEn: "'A witch scratched me, a man stabbed my leg, a monster beat me with a club,' the robber gasped to his friends, 'and on the roof a judge shouted: Bring the rogue to me!' The robbers never went near the house again.", textId: "'Penyihir mencakarku, seorang pria menusuk kakiku, monster memukulku dengan pentungan,' perampok itu tersengal pada kawan-kawannya, 'dan di atap seorang hakim berteriak: Bawa penjahat itu padaku!' Para perampok tak pernah berani mendekati rumah itu lagi." },
      { illustrationSeed: "bremen-13", textEn: "As for the four musicians, they liked their little house in the forest so well that they never went to Bremen at all. They had found something better than a stage: a home, and each other.", textId: "Adapun keempat pemusik, mereka begitu betah di rumah kecil di hutan itu hingga tak pernah pergi ke Bremen sama sekali. Mereka menemukan sesuatu yang lebih baik daripada panggung: sebuah rumah, dan satu sama lain." },
      { illustrationSeed: "bremen-14", textEn: "For no one is ever too old to start again, say the Brothers Grimm — and friends who sing together are never homeless. The end.", textId: "Sebab tak ada yang terlalu tua untuk memulai lagi, kata Grimm bersaudara — dan sahabat yang bernyanyi bersama tak akan pernah kehilangan rumah. Tamat." },
    ],
    quiz: [
      { questionEn: "Why did the animals leave their homes?", questionId: "Mengapa hewan-hewan itu meninggalkan rumah mereka?", optionsEn: ["They were bored", "Their owners no longer wanted them", "They loved music", "They were lost"], optionsId: ["Mereka bosan", "Pemiliknya tak menginginkan mereka lagi", "Mereka cinta musik", "Mereka tersesat"], correctIndex: 1 },
      { questionEn: "How did they scare the robbers the first time?", questionId: "Bagaimana mereka mengusir perampok pertama kali?", optionsEn: ["They called the police", "They made loud music together and crashed in", "They threw stones", "They lit a fire"], optionsId: ["Memanggil polisi", "Bermusik keras bersama dan menerjang masuk", "Melempar batu", "Menyalakan api"], correctIndex: 1 },
      { questionEn: "What did the four friends find in the end?", questionId: "Apa yang akhirnya ditemukan keempat sahabat?", optionsEn: ["Gold", "A stage in Bremen", "A home together", "A new master"], optionsId: ["Emas", "Panggung di Bremen", "Rumah bersama", "Tuan baru"], correctIndex: 2 },
    ],
  },
];

