/**
 * World folk tales — batch 2. Ten more long read-aloud children's stories
 * retold in the platform's own words from classic PUBLIC-DOMAIN folklore
 * (Aesop, Grimm, Panchatantra, Nusantara and Chinese tales). Bilingual EN/ID
 * with gentle comprehension quizzes, concatenated into STORIES (stories.ts)
 * so `npm run generate:seed` writes them straight into seed/seed.sql.
 */
import type { Story } from "./stories";

export const WORLD_STORIES_2: Story[] = [
  {
    slug: "the-tortoise-and-the-hare",
    titleEn: "The Tortoise and the Hare",
    titleId: "Kura-kura dan Kelinci",
    descriptionEn: "The fastest runner in the meadow laughs at the slowest — until race day teaches everyone what steady really means.",
    descriptionId: "Pelari tercepat di padang menertawakan yang paling lambat — sampai hari perlombaan mengajarkan arti kata 'tekun' pada semua.",
    categorySlug: "moral-stories",
    authorSlug: "axto-creative-team",
    coverEmoji: "🐢",
    coverPalette: "meadow",
    ageMin: 3,
    ageMax: 8,
    isPremium: false,
    pages: [
      { illustrationSeed: "tortoise-hare-1", textEn: "In a wide green meadow lived a hare who could run like the wind. He knew it, too, and told everyone about it every single day.", textId: "Di padang hijau yang luas hiduplah seekor kelinci yang bisa berlari secepat angin. Ia tahu itu, dan menceritakannya kepada semua hewan setiap hari." },
      { illustrationSeed: "tortoise-hare-2", textEn: "'I am the fastest animal in the whole meadow!' he boasted. 'Nobody could ever beat me. Especially not... a tortoise!' And he laughed and laughed.", textId: "'Akulah hewan tercepat di seluruh padang!' sombongnya. 'Tak ada yang bisa mengalahkanku. Apalagi... seekor kura-kura!' Lalu ia tertawa terbahak-bahak." },
      { illustrationSeed: "tortoise-hare-3", textEn: "The old tortoise looked up slowly. 'Then let us race, friend hare,' she said in her calm, quiet voice. 'To the big oak tree on the hill.'", textId: "Kura-kura tua itu mengangkat kepalanya pelan-pelan. 'Kalau begitu, ayo kita berlomba, sahabat kelinci,' katanya dengan suara tenang. 'Sampai pohon ek besar di atas bukit.'" },
      { illustrationSeed: "tortoise-hare-4", textEn: "All the animals gathered to watch. The fox raised his paw. 'Ready... steady... GO!' The hare shot away like an arrow. The tortoise took one small step.", textId: "Semua hewan berkumpul untuk menonton. Rubah mengangkat cakarnya. 'Bersedia... siap... MULAI!' Kelinci melesat bagai anak panah. Kura-kura melangkah satu langkah kecil." },
      { illustrationSeed: "tortoise-hare-5", textEn: "In no time at all, the hare was so far ahead he could not even see the tortoise behind him. 'This is too easy,' he yawned. 'I have time for a little nap.'", textId: "Dalam sekejap, kelinci sudah jauh sekali di depan sampai kura-kura tak terlihat lagi. 'Ini terlalu mudah,' ia menguap. 'Aku masih sempat tidur sebentar.'" },
      { illustrationSeed: "tortoise-hare-6", textEn: "He curled up under a shady bush, and the warm afternoon sun soon rocked him into a deep, deep sleep.", textId: "Ia meringkuk di bawah semak yang teduh, dan matahari sore yang hangat segera membuainya ke dalam tidur yang sangat lelap." },
      { illustrationSeed: "tortoise-hare-7", textEn: "Meanwhile, the tortoise kept walking. Step... step... step. She did not stop to rest. She did not stop to chat. She just kept going, slow and steady.", textId: "Sementara itu, kura-kura terus berjalan. Langkah... langkah... langkah. Ia tak berhenti untuk beristirahat. Ia tak berhenti untuk mengobrol. Ia terus maju, pelan tapi pasti." },
      { illustrationSeed: "tortoise-hare-8", textEn: "She passed the sleeping hare very quietly. Her little legs were tired, but she whispered to herself: 'One more step. And one more. And one more.'", textId: "Ia melewati kelinci yang tertidur dengan sangat pelan. Kaki kecilnya lelah, tetapi ia berbisik pada dirinya: 'Satu langkah lagi. Satu lagi. Satu lagi.'" },
      { illustrationSeed: "tortoise-hare-9", textEn: "When the hare finally woke, the sun was already low. He stretched, laughed — and then he saw it: far up the hill, the tortoise was almost at the oak tree!", textId: "Ketika kelinci akhirnya terbangun, matahari sudah rendah. Ia menggeliat, tertawa — lalu ia melihatnya: jauh di atas bukit, kura-kura hampir sampai di pohon ek!" },
      { illustrationSeed: "tortoise-hare-10", textEn: "The hare ran faster than he had ever run in his life. His ears flew back, his paws barely touched the ground — but it was too late.", textId: "Kelinci berlari lebih cepat daripada yang pernah ia lakukan seumur hidupnya. Telinganya melambai ke belakang, kakinya nyaris tak menyentuh tanah — tapi semuanya terlambat." },
      { illustrationSeed: "tortoise-hare-11", textEn: "The tortoise touched the great oak tree, and the whole meadow cheered. 'Slow and steady wins the race!' cried the fox.", textId: "Kura-kura menyentuh pohon ek besar itu, dan seluruh padang bersorak. 'Pelan tapi pasti memenangkan lomba!' seru rubah." },
      { illustrationSeed: "tortoise-hare-12", textEn: "The hare hung his head — then he did something brave: he walked up and shook the tortoise's hand. 'You taught me a big lesson today, little friend.' And from that day, he never boasted again. The end.", textId: "Kelinci menundukkan kepala — lalu ia melakukan sesuatu yang berani: ia menghampiri dan menjabat tangan kura-kura. 'Kau mengajariku pelajaran besar hari ini, sahabat kecil.' Dan sejak hari itu, ia tak pernah menyombong lagi. Tamat." },
    ],
    quiz: [
      { questionEn: "Why did the hare lose the race?", questionId: "Mengapa kelinci kalah dalam perlombaan?", optionsEn: ["He hurt his leg", "He stopped to sleep", "He got lost"], optionsId: ["Kakinya terluka", "Ia berhenti untuk tidur", "Ia tersesat"], correctIndex: 1 },
      { questionEn: "What did the tortoise keep doing all through the race?", questionId: "Apa yang terus dilakukan kura-kura sepanjang lomba?", optionsEn: ["Resting under bushes", "Walking without stopping", "Asking for help"], optionsId: ["Beristirahat di bawah semak", "Berjalan tanpa berhenti", "Meminta bantuan"], correctIndex: 1 },
      { questionEn: "What lesson did the hare learn?", questionId: "Pelajaran apa yang didapat kelinci?", optionsEn: ["Never race again", "Boasting is fun", "Do not mock others; steady effort wins"], optionsId: ["Jangan pernah berlomba lagi", "Menyombong itu menyenangkan", "Jangan meremehkan orang lain; ketekunan yang menang"], correctIndex: 2 },
    ],
  },
  {
    slug: "the-honest-woodcutter",
    titleEn: "The Honest Woodcutter and the Golden Axe",
    titleId: "Penebang Kayu yang Jujur dan Kapak Emas",
    descriptionEn: "A poor woodcutter drops his only axe into the deep river — and a shining spirit rises with a test that will change his life.",
    descriptionId: "Seorang penebang kayu miskin menjatuhkan satu-satunya kapaknya ke sungai yang dalam — dan seorang peri sungai muncul membawa ujian yang mengubah hidupnya.",
    categorySlug: "manners",
    authorSlug: "axto-creative-team",
    coverEmoji: "🪓",
    coverPalette: "forest",
    ageMin: 4,
    ageMax: 9,
    isPremium: false,
    pages: [
      { illustrationSeed: "woodcutter-1", textEn: "Long ago, beside a deep green river, lived a poor woodcutter. Every morning he walked into the forest with his old iron axe — the only precious thing he owned.", textId: "Dahulu kala, di tepi sungai hijau yang dalam, hiduplah seorang penebang kayu miskin. Setiap pagi ia masuk hutan membawa kapak besinya yang tua — satu-satunya benda berharga miliknya." },
      { illustrationSeed: "woodcutter-2", textEn: "One day, as he chopped a tree that leaned over the water, his hands slipped. The axe flew from his fingers — splash! — and sank into the deepest part of the river.", textId: "Suatu hari, saat menebang pohon yang condong ke air, tangannya terpeleset. Kapak itu terlempar dari genggamannya — byur! — dan tenggelam ke bagian sungai yang paling dalam." },
      { illustrationSeed: "woodcutter-3", textEn: "The woodcutter sat on the bank and covered his face. 'Without my axe I cannot work. Without work I cannot eat. What will become of me?'", textId: "Penebang kayu itu duduk di tepi sungai dan menutupi wajahnya. 'Tanpa kapak aku tak bisa bekerja. Tanpa bekerja aku tak bisa makan. Bagaimana nasibku nanti?'" },
      { illustrationSeed: "woodcutter-4", textEn: "Suddenly the water began to glow. Out of the river rose a gentle spirit with eyes like moonlight. 'Why do you weep, woodcutter?' she asked.", textId: "Tiba-tiba air sungai mulai bercahaya. Dari dalam sungai muncul peri lembut bermata seperti cahaya bulan. 'Mengapa engkau menangis, penebang kayu?' tanyanya." },
      { illustrationSeed: "woodcutter-5", textEn: "'I have lost my axe in the river,' he said. The spirit smiled, dived down, and rose again holding an axe of pure shining gold. 'Is this yours?'", textId: "'Kapakku jatuh ke sungai,' katanya. Peri itu tersenyum, menyelam, lalu muncul kembali membawa kapak dari emas murni yang berkilauan. 'Inikah milikmu?'" },
      { illustrationSeed: "woodcutter-6", textEn: "The woodcutter's eyes grew wide — gold! Enough to buy food for years. But he shook his head. 'No, kind spirit. That is not my axe.'", textId: "Mata penebang kayu terbelalak — emas! Cukup untuk membeli makanan bertahun-tahun. Tapi ia menggeleng. 'Bukan, peri yang baik. Itu bukan kapakku.'" },
      { illustrationSeed: "woodcutter-7", textEn: "The spirit dived again and rose with an axe of bright silver. 'Then surely this one is yours?' Again the woodcutter shook his head. 'No. Mine was only old iron.'", textId: "Peri itu menyelam lagi dan muncul membawa kapak perak yang berkilap. 'Kalau begitu, pasti yang ini milikmu?' Penebang kayu kembali menggeleng. 'Bukan. Kapakku hanya besi tua.'" },
      { illustrationSeed: "woodcutter-8", textEn: "A third time the spirit dived, and this time she held up the old iron axe with its worn wooden handle. 'That one is mine!' cried the woodcutter joyfully.", textId: "Untuk ketiga kalinya peri itu menyelam, dan kali ini ia mengangkat kapak besi tua dengan gagang kayu yang usang. 'Yang itu milikku!' seru penebang kayu gembira." },
      { illustrationSeed: "woodcutter-9", textEn: "The spirit's smile shone brighter than the gold. 'You spoke the truth, though you are poor and gold was in your reach. Honesty like yours deserves a reward.'", textId: "Senyum peri itu bersinar lebih terang daripada emas. 'Engkau berkata jujur, padahal engkau miskin dan emas ada di depan mata. Kejujuran seperti ini pantas mendapat hadiah.'" },
      { illustrationSeed: "woodcutter-10", textEn: "'Take all three axes — the iron, the silver, and the gold. Let them remind you that a true heart is the greatest treasure of all.' And the river fell quiet again.", textId: "'Ambillah ketiga kapak ini — besi, perak, dan emas. Biarlah semuanya mengingatkanmu bahwa hati yang jujur adalah harta yang paling besar.' Lalu sungai itu tenang kembali." },
      { illustrationSeed: "woodcutter-11", textEn: "A greedy neighbour heard the story and threw his own axe into the river on purpose. When the spirit offered him the golden axe, he shouted, 'Yes! That one is mine!'", textId: "Seorang tetangga yang serakah mendengar kisah itu dan sengaja melempar kapaknya ke sungai. Ketika peri menawarkan kapak emas, ia berteriak, 'Ya! Itu milikku!'" },
      { illustrationSeed: "woodcutter-12", textEn: "The spirit looked at him sadly — and sank beneath the water, taking the golden axe, the silver axe, and even his own iron axe with her. He went home with nothing at all.", textId: "Peri itu memandangnya dengan sedih — lalu tenggelam ke dalam air, membawa kapak emas, kapak perak, bahkan kapak besinya sendiri. Ia pulang tanpa membawa apa-apa." },
      { illustrationSeed: "woodcutter-13", textEn: "But the honest woodcutter lived well and happily, and whenever anyone asked about his three axes, he would say: 'The gold is pretty — but the truth bought it.' The end.", textId: "Namun penebang kayu yang jujur hidup senang dan berkecukupan, dan bila ada yang bertanya tentang ketiga kapaknya, ia menjawab: 'Emas memang indah — tapi kejujuranlah yang membelinya.' Tamat." },
    ],
    quiz: [
      { questionEn: "What did the woodcutter say when shown the golden axe?", questionId: "Apa kata penebang kayu saat ditunjukkan kapak emas?", optionsEn: ["'That is mine!'", "'That is not my axe.'", "'Keep it for yourself.'"], optionsId: ["'Itu milikku!'", "'Itu bukan kapakku.'", "'Simpan saja untukmu.'"], correctIndex: 1 },
      { questionEn: "Why did the spirit give him all three axes?", questionId: "Mengapa peri memberinya ketiga kapak itu?", optionsEn: ["Because he cried loudly", "Because he was honest", "Because he asked politely"], optionsId: ["Karena ia menangis keras", "Karena ia jujur", "Karena ia meminta dengan sopan"], correctIndex: 1 },
      { questionEn: "What happened to the greedy neighbour?", questionId: "Apa yang terjadi pada tetangga yang serakah?", optionsEn: ["He got the golden axe", "He lost even his own axe", "He became the spirit's friend"], optionsId: ["Ia mendapat kapak emas", "Ia kehilangan kapaknya sendiri", "Ia menjadi sahabat peri"], correctIndex: 1 },
    ],
  },
  {
    slug: "sang-kancil-and-the-crocodiles",
    titleEn: "Sang Kancil and the Crocodiles",
    titleId: "Sang Kancil dan Buaya-buaya",
    descriptionEn: "A tiny mouse-deer must cross a river full of hungry crocodiles — armed with nothing but a very big idea.",
    descriptionId: "Kancil kecil harus menyeberangi sungai yang penuh buaya lapar — hanya berbekal satu ide yang sangat besar.",
    categorySlug: "world-cultures",
    authorSlug: "siti-aminah",
    coverEmoji: "🐊",
    coverPalette: "ocean",
    ageMin: 3,
    ageMax: 8,
    isPremium: false,
    pages: [
      { illustrationSeed: "kancil-1", textEn: "In the warm forests of the Nusantara lived Sang Kancil, the mouse-deer — the smallest of the big animals and the cleverest of the small ones.", textId: "Di hutan Nusantara yang hangat hiduplah Sang Kancil — yang paling kecil di antara hewan besar, dan yang paling cerdik di antara hewan kecil." },
      { illustrationSeed: "kancil-2", textEn: "One morning, Kancil saw the ripest, sweetest rambutan trees he had ever seen — on the other side of the wide brown river.", textId: "Suatu pagi, Kancil melihat pohon rambutan paling ranum dan manis yang pernah ia lihat — di seberang sungai cokelat yang lebar." },
      { illustrationSeed: "kancil-3", textEn: "But the river was full of crocodiles. Big ones, long ones, hungry ones. Their yellow eyes watched Kancil from the water like floating lanterns.", textId: "Tapi sungai itu penuh buaya. Yang besar, yang panjang, yang lapar. Mata kuning mereka mengawasi Kancil dari dalam air seperti lentera terapung." },
      { illustrationSeed: "kancil-4", textEn: "Kancil thought and thought. Then he smiled his small clever smile, stood tall on a rock, and called out: 'Crocodiles! Wonderful news! The King has sent me to count you all for a great feast!'", textId: "Kancil berpikir dan berpikir. Lalu ia tersenyum kecil penuh akal, berdiri di atas batu, dan berseru: 'Buaya-buaya! Kabar gembira! Raja mengutusku menghitung kalian semua untuk pesta besar!'" },
      { illustrationSeed: "kancil-5", textEn: "'A feast?' the biggest crocodile rumbled, lifting his huge head. 'With food for all of us?' — 'Mountains of it!' said Kancil. 'But only crocodiles who are counted may come!'", textId: "'Pesta?' gumam buaya terbesar sambil mengangkat kepala raksasanya. 'Dengan makanan untuk kami semua?' — 'Bergunung-gunung!' kata Kancil. 'Tapi hanya buaya yang terhitung yang boleh datang!'" },
      { illustrationSeed: "kancil-6", textEn: "'Then count us! Count us!' the crocodiles cried. 'Very well,' said Kancil. 'Line up from this bank to the far bank — straight and still, nose to tail, so I miss nobody!'", textId: "'Kalau begitu hitunglah kami! Hitung kami!' seru para buaya. 'Baiklah,' kata Kancil. 'Berbarislah dari tepi sini sampai tepi seberang — lurus dan diam, dari hidung ke ekor, supaya tak ada yang terlewat!'" },
      { illustrationSeed: "kancil-7", textEn: "The crocodiles hurried into a line across the river, floating side by side like a bridge of bumpy green logs.", textId: "Buaya-buaya bergegas berbaris melintasi sungai, mengapung berdampingan seperti jembatan dari batang kayu hijau yang berbonggol-bonggol." },
      { illustrationSeed: "kancil-8", textEn: "'One!' said Kancil, hopping onto the first crocodile's back. 'Two!' — hop. 'Three!' — hop. He counted his way lightly across the whole river.", textId: "'Satu!' kata Kancil sambil melompat ke punggung buaya pertama. 'Dua!' — lompat. 'Tiga!' — lompat. Ia menghitung sambil melompat ringan menyeberangi seluruh sungai." },
      { illustrationSeed: "kancil-9", textEn: "'...and TWELVE!' he cried, landing safely on the far bank, right beneath the rambutan trees. The crocodiles waited eagerly. 'And now? When is the feast?'", textId: "'...dan DUA BELAS!' serunya sambil mendarat selamat di tepi seberang, tepat di bawah pohon rambutan. Para buaya menunggu tak sabar. 'Lalu? Kapan pestanya?'" },
      { illustrationSeed: "kancil-10", textEn: "Kancil picked a sweet rambutan and grinned. 'Thank you for the bridge, friends! The only feast today is mine!' And he skipped away into the trees.", textId: "Kancil memetik rambutan manis dan menyeringai. 'Terima kasih atas jembatannya, kawan-kawan! Satu-satunya pesta hari ini adalah pestaku!' Lalu ia melompat riang ke balik pepohonan." },
      { illustrationSeed: "kancil-11", textEn: "The crocodiles snapped and splashed and grumbled all afternoon. But secretly, even the biggest one had to admit: 'That little Kancil... has a very big brain.'", textId: "Para buaya menggertak, mencipratkan air, dan menggerutu sepanjang sore. Tapi diam-diam, buaya terbesar pun harus mengakui: 'Kancil kecil itu... otaknya besar sekali.'" },
      { illustrationSeed: "kancil-12", textEn: "And that is why, to this day, parents in the Nusantara tell their children: when the problem is bigger than you are, think bigger than the problem. The end.", textId: "Dan itulah sebabnya, sampai hari ini, orang tua di Nusantara berpesan kepada anak-anaknya: bila masalah lebih besar daripada dirimu, berpikirlah lebih besar daripada masalahmu. Tamat." },
    ],
    quiz: [
      { questionEn: "Why did Kancil need to cross the river?", questionId: "Mengapa Kancil perlu menyeberangi sungai?", optionsEn: ["To visit the King", "To reach the sweet rambutan trees", "To swim with the crocodiles"], optionsId: ["Untuk menemui Raja", "Untuk mencapai pohon rambutan yang manis", "Untuk berenang dengan buaya"], correctIndex: 1 },
      { questionEn: "How did Kancil get the crocodiles to make a bridge?", questionId: "Bagaimana Kancil membuat buaya-buaya menjadi jembatan?", optionsEn: ["He said the King wanted to count them for a feast", "He paid them with fruit", "He asked politely"], optionsId: ["Ia berkata Raja ingin menghitung mereka untuk pesta", "Ia membayar mereka dengan buah", "Ia meminta dengan sopan"], correctIndex: 0 },
      { questionEn: "What is the lesson of the story?", questionId: "Apa pelajaran dari cerita ini?", optionsEn: ["Crocodiles are kind", "Being big always wins", "A clever mind can solve a big problem"], optionsId: ["Buaya itu baik hati", "Yang besar selalu menang", "Akal yang cerdik bisa memecahkan masalah besar"], correctIndex: 2 },
    ],
  },
  {
    slug: "the-crow-and-the-pitcher",
    titleEn: "The Crow and the Pitcher",
    titleId: "Gagak dan Kendi Air",
    descriptionEn: "A thirsty crow finds water she cannot reach — and shows that patience plus a good idea can move the impossible.",
    descriptionId: "Seekor gagak yang kehausan menemukan air yang tak terjangkau — dan membuktikan bahwa kesabaran dan ide cerdas bisa mengalahkan yang mustahil.",
    categorySlug: "science",
    authorSlug: "axto-creative-team",
    coverEmoji: "🐦‍⬛",
    coverPalette: "dusk",
    ageMin: 3,
    ageMax: 7,
    isPremium: false,
    pages: [
      { illustrationSeed: "crow-pitcher-1", textEn: "It had not rained for many, many days. The streams were dry, the puddles were gone, and a tired crow flew across the hot fields looking for one thing only: water.", textId: "Hujan tak turun berhari-hari lamanya. Sungai kecil mengering, genangan lenyap, dan seekor gagak yang lelah terbang melintasi ladang panas mencari satu hal saja: air." },
      { illustrationSeed: "crow-pitcher-2", textEn: "Her throat burned and her wings felt heavy. 'Water,' she croaked. 'Just a little water...'", textId: "Tenggorokannya terasa terbakar dan sayapnya berat. 'Air,' seraknya. 'Sedikit saja air...'" },
      { illustrationSeed: "crow-pitcher-3", textEn: "Then, near an old farmhouse, she saw it: a tall clay pitcher! She peered inside — and yes! At the very bottom gleamed a little pool of cool, clear water.", textId: "Lalu, di dekat rumah tani tua, ia melihatnya: sebuah kendi tanah liat yang tinggi! Ia mengintip ke dalam — dan ya! Di dasar kendi berkilau sedikit air yang sejuk dan jernih." },
      { illustrationSeed: "crow-pitcher-4", textEn: "She pushed her beak into the pitcher. Too short! The water lay far below, and the pitcher's neck was narrow and deep.", textId: "Ia memasukkan paruhnya ke dalam kendi. Terlalu pendek! Air itu jauh di bawah, dan leher kendi sempit lagi dalam." },
      { illustrationSeed: "crow-pitcher-5", textEn: "She pushed the pitcher with her wings — it was too heavy to tip. She flapped and pecked and pushed again. Nothing. The water only trembled, far out of reach.", textId: "Ia mendorong kendi dengan sayapnya — terlalu berat untuk dimiringkan. Ia mengepak, mematuk, dan mendorong lagi. Sia-sia. Air itu hanya bergetar, jauh dari jangkauan." },
      { illustrationSeed: "crow-pitcher-6", textEn: "Many birds would have flown away. But this crow sat down, tilted her shiny black head, and looked at the problem the way clever birds do.", textId: "Burung lain mungkin sudah terbang pergi. Tapi gagak ini duduk, memiringkan kepala hitamnya yang berkilau, dan menatap masalah itu seperti burung-burung cerdik biasanya." },
      { illustrationSeed: "crow-pitcher-7", textEn: "Beside the pitcher lay a scattering of small pebbles. The crow looked at the pebbles. She looked at the water. And her bright eyes sparkled with an idea.", textId: "Di samping kendi berserakan kerikil-kerikil kecil. Gagak menatap kerikil. Ia menatap air. Dan matanya yang cerah berbinar oleh sebuah ide." },
      { illustrationSeed: "crow-pitcher-8", textEn: "She picked up a pebble and dropped it into the pitcher. Plop! The water rose — just a tiny, tiny bit.", textId: "Ia mengambil sebutir kerikil dan menjatuhkannya ke dalam kendi. Plung! Air naik — sedikit, sedikit sekali." },
      { illustrationSeed: "crow-pitcher-9", textEn: "Another pebble. Plop! And another. Plop! Pebble after pebble, the busy crow worked in the hot sun, and pebble after pebble, the water crept higher.", textId: "Kerikil lagi. Plung! Lagi. Plung! Kerikil demi kerikil, gagak yang rajin itu bekerja di bawah matahari panas, dan kerikil demi kerikil, air merayap semakin tinggi." },
      { illustrationSeed: "crow-pitcher-10", textEn: "At last — plop! — the water rose right up to the pitcher's neck. The crow dipped her beak and drank the sweetest, coolest drink of her whole life.", textId: "Akhirnya — plung! — air naik sampai ke leher kendi. Gagak mencelupkan paruhnya dan meneguk minuman termanis dan tersejuk sepanjang hidupnya." },
      { illustrationSeed: "crow-pitcher-11", textEn: "'Little by little does the trick,' she said happily, ruffling her feathers. And she flew off into the evening, strong and quick again.", textId: "'Sedikit demi sedikit, akhirnya berhasil,' katanya senang sambil mengibaskan bulunya. Lalu ia terbang ke senja, kembali kuat dan gesit." },
      { illustrationSeed: "crow-pitcher-12", textEn: "So when a problem looks too big, remember the crow: do not give up — think, start small, and keep going. Drop by drop, the water rises. The end.", textId: "Maka bila sebuah masalah tampak terlalu besar, ingatlah sang gagak: jangan menyerah — berpikirlah, mulailah dari yang kecil, dan teruslah berusaha. Setetes demi setetes, air akan naik. Tamat." },
    ],
    quiz: [
      { questionEn: "Why couldn't the crow drink at first?", questionId: "Mengapa gagak tak bisa langsung minum?", optionsEn: ["The water was too deep inside the pitcher", "The water was dirty", "The pitcher was empty"], optionsId: ["Airnya terlalu dalam di dasar kendi", "Airnya kotor", "Kendinya kosong"], correctIndex: 0 },
      { questionEn: "What did the crow drop into the pitcher?", questionId: "Apa yang dijatuhkan gagak ke dalam kendi?", optionsEn: ["Leaves", "Pebbles", "Seeds"], optionsId: ["Daun", "Kerikil", "Biji-bijian"], correctIndex: 1 },
      { questionEn: "What made the water rise?", questionId: "Apa yang membuat air naik?", optionsEn: ["Magic", "Each pebble taking up space", "The hot sun"], optionsId: ["Sihir", "Setiap kerikil memenuhi ruang di dalam air", "Matahari yang panas"], correctIndex: 1 },
    ],
  },
  {
    slug: "the-elves-and-the-shoemaker",
    titleEn: "The Elves and the Shoemaker",
    titleId: "Peri Kecil dan Tukang Sepatu",
    descriptionEn: "A kind old shoemaker is down to his last piece of leather — until tiny midnight helpers change everything, and kindness is repaid with kindness.",
    descriptionId: "Tukang sepatu tua yang baik hati hanya punya selembar kulit terakhir — sampai para penolong mungil tengah malam mengubah segalanya, dan kebaikan dibalas kebaikan.",
    categorySlug: "fairy-tales",
    authorSlug: "axto-creative-team",
    coverEmoji: "👞",
    coverPalette: "night",
    ageMin: 4,
    ageMax: 9,
    isPremium: false,
    pages: [
      { illustrationSeed: "elves-shoemaker-1", textEn: "There was once a shoemaker who was honest and kind, but times were hard, and one evening he found he had leather left for only one last pair of shoes.", textId: "Dahulu ada seorang tukang sepatu yang jujur dan baik hati, tetapi zaman sedang sulit, dan suatu malam ia sadar kulitnya hanya cukup untuk satu pasang sepatu terakhir." },
      { illustrationSeed: "elves-shoemaker-2", textEn: "He cut the leather carefully, laid the pieces on his workbench, and sighed. 'I will sew them in the morning.' Then he blew out the candle and went to bed.", textId: "Ia memotong kulit itu dengan hati-hati, menata potongannya di meja kerja, lalu menghela napas. 'Besok pagi akan kujahit.' Kemudian ia meniup lilin dan pergi tidur." },
      { illustrationSeed: "elves-shoemaker-3", textEn: "But in the morning — what a wonder! On the bench stood a finished pair of shoes, so beautifully stitched that every seam was perfect. 'Who could have done this?'", textId: "Namun pagi harinya — sungguh ajaib! Di atas meja sudah berdiri sepasang sepatu jadi, dijahit begitu indah hingga setiap jahitannya sempurna. 'Siapa gerangan yang mengerjakan ini?'" },
      { illustrationSeed: "elves-shoemaker-4", textEn: "A rich traveller bought the shoes at once, and paid so well that the shoemaker could buy leather for two pairs. That night, he cut the pieces and left them out again.", textId: "Seorang pelancong kaya langsung membeli sepatu itu, dan membayar sangat mahal hingga tukang sepatu bisa membeli kulit untuk dua pasang. Malam itu ia memotong kulitnya dan menaruhnya lagi di meja." },
      { illustrationSeed: "elves-shoemaker-5", textEn: "In the morning, two perfect pairs! And so it went on, night after night: whatever he cut in the evening was finished by dawn, finer than any shoes in the town.", textId: "Paginya, dua pasang sepatu sempurna! Begitu seterusnya, malam demi malam: apa pun yang ia potong di senja hari selesai saat fajar, lebih bagus daripada sepatu mana pun di kota." },
      { illustrationSeed: "elves-shoemaker-6", textEn: "The little shop grew busy and warm again. But the shoemaker and his wife could not stop wondering. 'Tonight,' said his wife, 'let us hide behind the curtain and watch.'", textId: "Toko kecil itu kembali ramai dan hangat. Tapi tukang sepatu dan istrinya tak bisa berhenti bertanya-tanya. 'Malam ini,' kata istrinya, 'mari kita sembunyi di balik tirai dan mengintip.'" },
      { illustrationSeed: "elves-shoemaker-7", textEn: "At midnight, the window creaked open — and in slipped two tiny elves, no taller than teacups. Their little clothes were nothing but rags, but their hands flew like hummingbirds.", textId: "Tepat tengah malam, jendela berderit terbuka — dan masuklah dua peri mungil, tak lebih tinggi dari cangkir teh. Pakaian kecil mereka hanya kain compang-camping, tetapi tangan mereka bekerja secepat kolibri." },
      { illustrationSeed: "elves-shoemaker-8", textEn: "Snip, stitch, tap-tap-tap! In moments the shoes stood finished, gleaming in the moonlight. Then the little elves bowed to each other and slipped away into the night.", textId: "Gunting, jahit, tok-tok-tok! Dalam sekejap sepatu-sepatu itu selesai, berkilau dalam cahaya bulan. Lalu kedua peri kecil saling membungkuk dan menghilang ke dalam malam." },
      { illustrationSeed: "elves-shoemaker-9", textEn: "'They work so hard for us,' whispered the shoemaker's wife, 'and their clothes are so thin and torn. Winter is coming. Let us make a gift for them!'", textId: "'Mereka bekerja begitu keras untuk kita,' bisik istri tukang sepatu, 'padahal baju mereka tipis dan robek. Musim dingin akan tiba. Mari kita buatkan hadiah untuk mereka!'" },
      { illustrationSeed: "elves-shoemaker-10", textEn: "So they sewed two tiny shirts, two tiny coats, two tiny caps — and the shoemaker made the smallest, softest pair of boots his hands had ever made.", textId: "Maka mereka menjahit dua kemeja mungil, dua mantel mungil, dua topi mungil — dan tukang sepatu membuat sepasang sepatu bot terkecil dan terlembut yang pernah dibuat tangannya." },
      { illustrationSeed: "elves-shoemaker-11", textEn: "That night they laid the little clothes on the bench instead of leather. When the elves arrived, they clapped their tiny hands with joy, dressed at once, and danced around the workbench!", textId: "Malam itu mereka menaruh pakaian mungil di meja, bukan kulit sepatu. Ketika para peri datang, mereka bertepuk tangan gembira, langsung berpakaian, dan menari-nari mengelilingi meja kerja!" },
      { illustrationSeed: "elves-shoemaker-12", textEn: "'Now we are dressed so fine and neat — no more cobbling, dancing feet!' they sang, and out of the window they twirled, never to be seen again.", textId: "'Kini kami berpakaian rapi dan indah — tak lagi menjahit, kaki kami menari!' nyanyi mereka, lalu berputar keluar jendela, dan tak pernah terlihat lagi." },
      { illustrationSeed: "elves-shoemaker-13", textEn: "But good luck never left that little shop. For kindness given in secret has a way of staying in the walls — and in every pair of shoes the old man made, people said they could feel it. The end.", textId: "Namun keberuntungan tak pernah meninggalkan toko kecil itu. Sebab kebaikan yang diberikan diam-diam selalu tinggal di dinding rumah — dan pada setiap pasang sepatu buatan pak tua itu, kata orang, kebaikan itu terasa. Tamat." },
    ],
    quiz: [
      { questionEn: "Who finished the shoes at night?", questionId: "Siapa yang menyelesaikan sepatu di malam hari?", optionsEn: ["The shoemaker's wife", "Two tiny elves", "The rich traveller"], optionsId: ["Istri tukang sepatu", "Dua peri mungil", "Pelancong kaya"], correctIndex: 1 },
      { questionEn: "What gift did the shoemaker and his wife make?", questionId: "Hadiah apa yang dibuat tukang sepatu dan istrinya?", optionsEn: ["Tiny clothes and boots", "A little house", "Golden coins"], optionsId: ["Pakaian dan sepatu bot mungil", "Rumah kecil", "Koin emas"], correctIndex: 0 },
      { questionEn: "Why did they give the elves a gift?", questionId: "Mengapa mereka memberi hadiah kepada para peri?", optionsEn: ["To make them work harder", "To thank them for their secret kindness", "To make them leave"], optionsId: ["Agar mereka bekerja lebih keras", "Untuk berterima kasih atas kebaikan diam-diam mereka", "Agar mereka pergi"], correctIndex: 1 },
    ],
  },
  {
    slug: "the-town-mouse-and-the-country-mouse",
    titleEn: "The Town Mouse and the Country Mouse",
    titleId: "Tikus Kota dan Tikus Desa",
    descriptionEn: "Two cousin mice visit each other's worlds — fine food in the noisy town, simple food in the peaceful field — and discover what 'home' really tastes like.",
    descriptionId: "Dua tikus bersaudara saling mengunjungi dunia masing-masing — makanan mewah di kota yang bising, makanan sederhana di ladang yang damai — dan menemukan rasa 'rumah' yang sesungguhnya.",
    categorySlug: "family",
    authorSlug: "axto-creative-team",
    coverEmoji: "🐭",
    coverPalette: "candy",
    ageMin: 3,
    ageMax: 8,
    isPremium: false,
    pages: [
      { illustrationSeed: "town-country-1", textEn: "Once there were two cousin mice. One lived in the quiet countryside, in a snug burrow under a hazel hedge. The other lived in the big, busy town, inside the wall of a grand house.", textId: "Dahulu ada dua tikus bersaudara sepupu. Yang satu tinggal di desa yang tenang, dalam liang hangat di bawah pagar tanaman. Yang lain tinggal di kota besar yang sibuk, di balik dinding sebuah rumah megah." },
      { illustrationSeed: "town-country-2", textEn: "One autumn day, the town mouse came to visit. The country mouse proudly served the best he had: barley grains, hazelnuts, and a little piece of cheese rind.", textId: "Suatu hari di musim gugur, tikus kota datang berkunjung. Tikus desa dengan bangga menghidangkan yang terbaik miliknya: butir jelai, kacang hazel, dan sepotong kecil kulit keju." },
      { illustrationSeed: "town-country-3", textEn: "The town mouse nibbled politely, then wrinkled his nose. 'Dear cousin, how do you bear such plain food and such a quiet life? Come with me to town — I shall show you how to truly live!'", textId: "Tikus kota mengunyah dengan sopan, lalu mengernyitkan hidungnya. 'Saudaraku, bagaimana kau tahan dengan makanan sederhana dan hidup sesunyi ini? Ikutlah ke kota — akan kutunjukkan cara hidup yang sesungguhnya!'" },
      { illustrationSeed: "town-country-4", textEn: "So off they went. The town glittered with a thousand lights. In the grand house, the dining table was still covered from a feast: cakes, cheeses, figs, and honey!", textId: "Maka berangkatlah mereka. Kota berkilauan dengan seribu lampu. Di rumah megah itu, meja makan masih penuh sisa pesta: kue, keju, buah ara, dan madu!" },
      { illustrationSeed: "town-country-5", textEn: "'Help yourself, cousin!' said the town mouse grandly. The country mouse had never tasted anything so delicious in all his life. 'Why, this is wonderful!' he squeaked.", textId: "'Silakan makan sepuasnya, saudaraku!' kata tikus kota dengan megah. Tikus desa belum pernah mencicipi makanan selezat itu seumur hidupnya. 'Wah, ini luar biasa!' cicitnya." },
      { illustrationSeed: "town-country-6", textEn: "But just as he bit into a fig — BANG! — the door flew open. Servants marched in with heavy boots, and the two mice dashed behind the curtain, hearts drumming.", textId: "Namun tepat saat ia menggigit buah ara — BRAK! — pintu terbuka lebar. Para pelayan masuk dengan sepatu bot berat, dan kedua tikus melesat ke balik tirai, jantung berdebar kencang." },
      { illustrationSeed: "town-country-7", textEn: "When all was quiet, they crept out again. But hardly had they reached the cheese — 'MEOW!' A huge cat leapt onto the table, eyes blazing like green fire!", textId: "Setelah semuanya sunyi, mereka merayap keluar lagi. Namun belum sampai ke keju — 'MEONG!' Seekor kucing besar melompat ke atas meja, matanya menyala seperti api hijau!" },
      { illustrationSeed: "town-country-8", textEn: "The mice tumbled into a crack in the wall just in time. The country mouse pressed his paws to his chest. 'Cousin... is it like this every day?' — 'Oh, one gets used to it,' said the town mouse airily.", textId: "Kedua tikus terguling masuk celah dinding tepat pada waktunya. Tikus desa mendekap dadanya. 'Saudaraku... apakah setiap hari seperti ini?' — 'Ah, lama-lama juga terbiasa,' jawab tikus kota enteng." },
      { illustrationSeed: "town-country-9", textEn: "That night, the country mouse lay awake listening to carriages rattle and doors slam. He thought of his hedge, where the loudest sound was the owl saying goodnight.", textId: "Malam itu, tikus desa terjaga mendengarkan kereta kuda berderak dan pintu-pintu dibanting. Ia teringat pagar tanamannya, tempat suara paling nyaring hanyalah burung hantu yang mengucap selamat malam." },
      { illustrationSeed: "town-country-10", textEn: "In the morning he hugged his cousin. 'Thank you for the feast, truly. But I would rather eat barley in peace than honey in fear. My little hedge is calling me home.'", textId: "Paginya ia memeluk sepupunya. 'Sungguh terima kasih atas pestanya. Tapi aku lebih suka makan jelai dalam damai daripada madu dalam ketakutan. Pagar kecilku memanggilku pulang.'" },
      { illustrationSeed: "town-country-11", textEn: "Back under the hazel hedge, he cooked his plain barley supper and ate it slowly, listening to the wind in the leaves. It tasted, he thought, exactly like happiness.", textId: "Kembali di bawah pagar tanamannya, ia memasak jelai sederhana untuk makan malam dan menyantapnya pelan-pelan sambil mendengarkan angin di dedaunan. Rasanya, pikirnya, persis seperti kebahagiaan." },
      { illustrationSeed: "town-country-12", textEn: "For a simple life in peace can be sweeter than a rich life in fear — and the best home is the one where your heart can rest. The end.", textId: "Sebab hidup sederhana yang damai bisa lebih manis daripada hidup mewah yang penuh ketakutan — dan rumah terbaik adalah tempat hatimu bisa beristirahat. Tamat." },
    ],
    quiz: [
      { questionEn: "What food did the country mouse serve?", questionId: "Makanan apa yang dihidangkan tikus desa?", optionsEn: ["Cakes and honey", "Barley, hazelnuts and cheese rind", "Figs and cream"], optionsId: ["Kue dan madu", "Jelai, kacang hazel, dan kulit keju", "Buah ara dan krim"], correctIndex: 1 },
      { questionEn: "What dangers did the mice meet in town?", questionId: "Bahaya apa yang mereka temui di kota?", optionsEn: ["Rain and thunder", "Servants and a huge cat", "A hungry owl"], optionsId: ["Hujan dan petir", "Para pelayan dan kucing besar", "Burung hantu lapar"], correctIndex: 1 },
      { questionEn: "What did the country mouse decide in the end?", questionId: "Apa keputusan tikus desa pada akhirnya?", optionsEn: ["To stay in town forever", "That peace at home is sweeter than riches in fear", "To become a town mouse"], optionsId: ["Tinggal di kota selamanya", "Damai di rumah lebih manis daripada kemewahan dalam ketakutan", "Menjadi tikus kota"], correctIndex: 1 },
    ],
  },
  {
    slug: "the-little-red-hen",
    titleEn: "The Little Red Hen",
    titleId: "Ayam Merah Kecil",
    descriptionEn: "Who will help plant the wheat? Not I, said the cat, the dog and the duck — a warm farm tale about work, sharing, and second chances.",
    descriptionId: "Siapa mau membantu menanam gandum? Tidak aku, kata kucing, anjing, dan bebek — dongeng peternakan yang hangat tentang kerja, berbagi, dan kesempatan kedua.",
    categorySlug: "farm",
    authorSlug: "axto-creative-team",
    coverEmoji: "🐔",
    coverPalette: "sunrise",
    ageMin: 3,
    ageMax: 7,
    isPremium: false,
    pages: [
      { illustrationSeed: "red-hen-1", textEn: "On a cosy little farm lived a little red hen with her fluffy yellow chicks — and three lazy friends: a sleepy cat, a dozy dog, and a daydreaming duck.", textId: "Di sebuah peternakan kecil yang nyaman hiduplah ayam merah kecil bersama anak-anaknya yang kuning berbulu halus — dan tiga sahabat pemalas: kucing yang mengantuk, anjing yang lesu, dan bebek yang suka melamun." },
      { illustrationSeed: "red-hen-2", textEn: "One bright morning, the little red hen found some golden grains of wheat on the path. 'Who will help me plant this wheat?' she called.", textId: "Suatu pagi yang cerah, ayam merah kecil menemukan butir-butir gandum keemasan di jalan setapak. 'Siapa mau membantuku menanam gandum ini?' serunya." },
      { illustrationSeed: "red-hen-3", textEn: "'Not I,' yawned the cat from the windowsill. 'Not I,' mumbled the dog from his shady spot. 'Not I,' quacked the duck, watching the clouds.", textId: "'Tidak aku,' kucing menguap dari jendela. 'Tidak aku,' gumam anjing dari tempat teduhnya. 'Tidak aku,' kwek bebek sambil menatap awan." },
      { illustrationSeed: "red-hen-4", textEn: "'Then I shall plant it myself,' said the little red hen. And she did — scratching the soil, tucking in each grain, and patting the earth gently on top.", textId: "'Kalau begitu akan kutanam sendiri,' kata ayam merah kecil. Dan ia melakukannya — mengais tanah, membenamkan setiap butir, dan menepuk-nepuk tanah dengan lembut." },
      { illustrationSeed: "red-hen-5", textEn: "All summer she watered and weeded. 'Who will help me care for the wheat?' — 'Not I.' 'Not I.' 'Not I.' So she cared for it herself, day after day.", textId: "Sepanjang musim ia menyiram dan mencabuti rumput liar. 'Siapa mau membantuku merawat gandum?' — 'Tidak aku.' 'Tidak aku.' 'Tidak aku.' Maka ia merawatnya sendiri, hari demi hari." },
      { illustrationSeed: "red-hen-6", textEn: "The wheat grew tall and golden as the sun. 'Who will help me cut the wheat?' asked the hen. 'Not I,' said the cat, the dog and the duck together.", textId: "Gandum tumbuh tinggi dan keemasan seperti matahari. 'Siapa mau membantuku memanen gandum?' tanya si ayam. 'Tidak aku,' jawab kucing, anjing, dan bebek serempak." },
      { illustrationSeed: "red-hen-7", textEn: "'Then I shall cut it myself.' Swish, swish! She cut and bundled every stalk, and carried it to the mill to be ground into soft white flour.", textId: "'Kalau begitu akan kupanen sendiri.' Kres, kres! Ia memotong dan mengikat setiap batang, lalu membawanya ke penggilingan untuk dijadikan tepung putih yang halus." },
      { illustrationSeed: "red-hen-8", textEn: "'Who will help me bake the bread?' she asked at last. 'Not I... not I... not I,' came the three lazy voices. 'Then I shall bake it myself,' said the little red hen.", textId: "'Siapa mau membantuku memanggang roti?' tanyanya akhirnya. 'Tidak aku... tidak aku... tidak aku,' sahut tiga suara pemalas itu. 'Kalau begitu akan kupanggang sendiri,' kata ayam merah kecil." },
      { illustrationSeed: "red-hen-9", textEn: "Soon a smell so warm and wonderful floated across the farm that the cat, the dog and the duck all came running. 'We will help you EAT the bread!' they cried.", textId: "Tak lama kemudian, aroma yang begitu hangat dan lezat tercium ke seluruh peternakan, sampai kucing, anjing, dan bebek berlari datang. 'Kami mau membantu MAKAN rotinya!' seru mereka." },
      { illustrationSeed: "red-hen-10", textEn: "The little red hen looked at them kindly but firmly. 'You did not plant, you did not water, you did not cut, you did not bake. My chicks and I, who did the work, will eat this loaf.'", textId: "Ayam merah kecil memandang mereka dengan lembut tapi tegas. 'Kalian tidak menanam, tidak menyiram, tidak memanen, tidak memanggang. Aku dan anak-anakku, yang mengerjakan semuanya, yang akan memakan roti ini.'" },
      { illustrationSeed: "red-hen-11", textEn: "The three friends hung their heads, for they knew she was right. 'We are sorry, little red hen,' said the dog quietly. 'Next time, we will help from the very first day.'", textId: "Ketiga sahabat itu menunduk malu, karena mereka tahu ayam merah benar. 'Maafkan kami, ayam merah kecil,' kata anjing pelan. 'Lain kali, kami akan membantu sejak hari pertama.'" },
      { illustrationSeed: "red-hen-12", textEn: "And they kept their word! When spring came, four friends planted the wheat together — and when the next loaf came out of the oven, the whole farm shared it, warm slice by warm slice. The end.", textId: "Dan mereka menepati janji! Saat musim semi tiba, empat sahabat menanam gandum bersama — dan ketika roti berikutnya keluar dari panggangan, seisi peternakan menikmatinya bersama, sepotong demi sepotong yang hangat. Tamat." },
    ],
    quiz: [
      { questionEn: "What did the friends say when the hen asked for help?", questionId: "Apa jawaban para sahabat saat si ayam minta tolong?", optionsEn: ["'Yes, of course!'", "'Not I.'", "'Maybe tomorrow.'"], optionsId: ["'Ya, tentu!'", "'Tidak aku.'", "'Mungkin besok.'"], correctIndex: 1 },
      { questionEn: "Why didn't the hen share the first loaf?", questionId: "Mengapa ayam tidak membagi roti pertamanya?", optionsEn: ["She was unkind", "The friends had refused to do any of the work", "The bread was too small"], optionsId: ["Ia jahat", "Para sahabat menolak ikut bekerja", "Rotinya terlalu kecil"], correctIndex: 1 },
      { questionEn: "What happened in spring?", questionId: "Apa yang terjadi saat musim semi?", optionsEn: ["The friends helped from the first day and all shared the bread", "The hen moved away", "The wheat did not grow"], optionsId: ["Para sahabat membantu sejak hari pertama dan semua berbagi roti", "Si ayam pindah", "Gandumnya tidak tumbuh"], correctIndex: 0 },
    ],
  },
  {
    slug: "the-boy-who-cried-wolf",
    titleEn: "The Boy Who Cried Wolf",
    titleId: "Anak Gembala yang Berteriak Serigala",
    descriptionEn: "A bored shepherd boy plays a trick on his village — twice. But when a real wolf comes, he learns what a lie costs.",
    descriptionId: "Seorang anak gembala yang bosan mengerjai desanya — dua kali. Namun saat serigala sungguhan datang, ia belajar mahalnya harga sebuah kebohongan.",
    categorySlug: "moral-stories",
    authorSlug: "axto-creative-team",
    coverEmoji: "🐺",
    coverPalette: "dusk",
    ageMin: 4,
    ageMax: 9,
    isPremium: false,
    pages: [
      { illustrationSeed: "cried-wolf-1", textEn: "On a green hill above a little village, a shepherd boy watched the sheep every day. The sun was warm, the bells went ting-ting, and the days were very, very long.", textId: "Di bukit hijau di atas sebuah desa kecil, seorang anak gembala menjaga domba setiap hari. Matahari hangat, lonceng domba berdenting-denting, dan hari terasa sangat, sangat panjang." },
      { illustrationSeed: "cried-wolf-2", textEn: "One afternoon, the boy grew so bored that a naughty idea popped into his head. He stood up, cupped his hands, and shouted down to the village: 'WOLF! WOLF! A wolf is after the sheep!'", textId: "Suatu sore, anak itu begitu bosan sampai sebuah ide nakal muncul di kepalanya. Ia berdiri, menangkupkan tangan, dan berteriak ke arah desa: 'SERIGALA! SERIGALA! Ada serigala mengejar domba!'" },
      { illustrationSeed: "cried-wolf-3", textEn: "The villagers dropped everything. The baker left his oven, the farmer left his plough, and up the hill they ran with sticks and shouts — as fast as their legs could carry them.", textId: "Warga desa meninggalkan semuanya. Tukang roti meninggalkan panggangannya, petani meninggalkan bajaknya, dan mereka berlari mendaki bukit membawa tongkat sambil berteriak — secepat kaki mereka bisa berlari." },
      { illustrationSeed: "cried-wolf-4", textEn: "But at the top they found no wolf at all — only the boy, rolling in the grass with laughter. 'You should see your faces!' he giggled. The villagers walked home, shaking their heads.", textId: "Namun di puncak bukit tak ada serigala sama sekali — hanya si anak, berguling-guling di rumput sambil tertawa. 'Coba lihat wajah kalian!' kikiknya. Warga desa pulang sambil menggeleng-geleng." },
      { illustrationSeed: "cried-wolf-5", textEn: "A few days later, the boy did it again. 'WOLF! WOLF!' And again the villagers came running — and again there was no wolf, only laughter rolling down the hill.", textId: "Beberapa hari kemudian, anak itu melakukannya lagi. 'SERIGALA! SERIGALA!' Dan lagi-lagi warga berlari datang — dan lagi-lagi tak ada serigala, hanya tawa yang bergema menuruni bukit." },
      { illustrationSeed: "cried-wolf-6", textEn: "This time nobody smiled. 'Lies are not jokes, boy,' said the old baker quietly. 'A liar is not believed — even when he tells the truth.' But the boy only shrugged.", textId: "Kali ini tak ada yang tersenyum. 'Bohong itu bukan lelucon, nak,' kata tukang roti tua pelan. 'Pembohong takkan dipercaya — bahkan saat ia berkata benar.' Tapi anak itu hanya mengangkat bahu." },
      { illustrationSeed: "cried-wolf-7", textEn: "Then, one grey evening, the grass rustled — and out of the shadows stepped a real wolf, with hungry yellow eyes fixed on the flock.", textId: "Lalu, pada suatu senja kelabu, rerumputan bergemerisik — dan dari balik bayangan muncullah serigala sungguhan, dengan mata kuning lapar menatap kawanan domba." },
      { illustrationSeed: "cried-wolf-8", textEn: "'WOLF!' screamed the boy, and this time his voice shook with real fear. 'WOLF! PLEASE! HELP! A REAL WOLF!'", textId: "'SERIGALA!' jerit anak itu, dan kali ini suaranya gemetar oleh ketakutan yang sungguhan. 'SERIGALA! TOLONG! SERIGALA BETULAN!'" },
      { illustrationSeed: "cried-wolf-9", textEn: "Down in the village, the baker heard him and sighed. 'That boy again.' The farmer heard him and kept ploughing. 'He will not fool us a third time.' Nobody came.", textId: "Di bawah, di desa, tukang roti mendengarnya dan menghela napas. 'Anak itu lagi.' Petani mendengarnya dan terus membajak. 'Ia takkan menipu kami untuk ketiga kalinya.' Tak seorang pun datang." },
      { illustrationSeed: "cried-wolf-10", textEn: "The boy could only wave his stick and shout as the wolf scattered the flock and drove off the fattest sheep into the dark woods.", textId: "Anak itu hanya bisa mengayunkan tongkat dan berteriak saat serigala mencerai-beraikan kawanan dan menggiring domba paling gemuk ke dalam hutan yang gelap." },
      { illustrationSeed: "cried-wolf-11", textEn: "When the villagers finally came at nightfall and heard what had happened, the boy hung his head and wept. 'You warned me,' he whispered to the baker. 'Nobody believes a liar — even when he tells the truth.'", textId: "Ketika warga akhirnya datang saat malam tiba dan mendengar kejadiannya, anak itu menunduk dan menangis. 'Kalian sudah memperingatkanku,' bisiknya pada tukang roti. 'Tak ada yang percaya pembohong — bahkan saat ia berkata benar.'" },
      { illustrationSeed: "cried-wolf-12", textEn: "From that day on, the boy guarded both his sheep and his words. And when he grew up, they say, he became the most trusted man in the village — because he had learned young how precious the truth is. The end.", textId: "Sejak hari itu, si anak menjaga dombanya dan juga kata-katanya. Dan ketika ia dewasa, konon ia menjadi orang paling dipercaya di desa — karena ia belajar sejak kecil betapa berharganya kejujuran. Tamat." },
    ],
    quiz: [
      { questionEn: "Why did the boy first shout 'Wolf!'?", questionId: "Mengapa anak itu pertama kali berteriak 'Serigala!'?", optionsEn: ["He saw a real wolf", "He was bored and wanted to trick the villagers", "He was practising singing"], optionsId: ["Ia melihat serigala sungguhan", "Ia bosan dan ingin mengerjai warga", "Ia sedang latihan bernyanyi"], correctIndex: 1 },
      { questionEn: "Why did nobody come when the real wolf appeared?", questionId: "Mengapa tak ada yang datang saat serigala sungguhan muncul?", optionsEn: ["They were asleep", "They no longer believed him after his lies", "They were afraid of wolves"], optionsId: ["Mereka sedang tidur", "Mereka tak lagi percaya setelah kebohongannya", "Mereka takut serigala"], correctIndex: 1 },
      { questionEn: "What is the lesson of this story?", questionId: "Apa pelajaran dari cerita ini?", optionsEn: ["Wolves are dangerous", "Shouting is rude", "If you lie, people stop believing you — even when you tell the truth"], optionsId: ["Serigala itu berbahaya", "Berteriak itu tidak sopan", "Jika kau berbohong, orang berhenti mempercayaimu — bahkan saat kau jujur"], correctIndex: 2 },
    ],
  },
  {
    slug: "the-monkey-and-the-crocodile",
    titleEn: "The Monkey and the Crocodile",
    titleId: "Kera dan Buaya",
    descriptionEn: "A monkey and a crocodile become unlikely river friends — until a dangerous secret tests how quickly a clever heart can think.",
    descriptionId: "Seekor kera dan buaya menjadi sahabat sungai yang tak terduga — sampai sebuah rahasia berbahaya menguji secepat apa akal yang cerdik bisa berpikir.",
    categorySlug: "jungle-safari",
    authorSlug: "axto-creative-team",
    coverEmoji: "🐒",
    coverPalette: "forest",
    ageMin: 4,
    ageMax: 9,
    isPremium: false,
    pages: [
      { illustrationSeed: "monkey-croc-1", textEn: "Long ago, in a jamun tree that leaned over a great river, lived a cheerful monkey. The tree's purple fruit was the sweetest for miles, and the monkey ate it from morning till night.", textId: "Dahulu kala, di pohon jamblang yang condong ke sungai besar, hiduplah seekor kera yang riang. Buah ungu pohon itu paling manis sejauh mata memandang, dan si kera memakannya dari pagi sampai malam." },
      { illustrationSeed: "monkey-croc-2", textEn: "One day a crocodile swam up and rested under the tree. 'You look tired, friend,' said the monkey, and he threw down a pawful of sweet jamun. The crocodile had never tasted anything so fine.", textId: "Suatu hari seekor buaya berenang mendekat dan beristirahat di bawah pohon. 'Kau tampak lelah, kawan,' kata kera, lalu ia menjatuhkan segenggam jamblang manis. Buaya itu belum pernah mencicipi buah selezat itu." },
      { illustrationSeed: "monkey-croc-3", textEn: "From then on, the crocodile came every day, and the two became true friends — the monkey dropping fruit, the crocodile telling stories of the deep river and the far bank.", textId: "Sejak itu, buaya datang setiap hari, dan keduanya menjadi sahabat sejati — kera menjatuhkan buah, buaya bercerita tentang sungai yang dalam dan tepian yang jauh." },
      { illustrationSeed: "monkey-croc-4", textEn: "The crocodile carried some jamun home to his wife. She ate them and her eyes narrowed greedily. 'If the fruit is this sweet,' she said, 'how sweet must be the heart of the monkey who eats them every day! Bring me his heart.'", textId: "Buaya membawa beberapa jamblang pulang untuk istrinya. Istrinya memakannya dan matanya menyipit serakah. 'Kalau buahnya semanis ini,' katanya, 'betapa manisnya hati kera yang memakannya setiap hari! Bawakan aku hati kera itu.'" },
      { illustrationSeed: "monkey-croc-5", textEn: "The crocodile was horrified. 'He is my friend!' But his wife pretended to be terribly ill. 'Only a monkey's heart can cure me,' she moaned. And the weak-willed crocodile finally agreed.", textId: "Buaya terkejut dan sedih. 'Ia sahabatku!' Tapi istrinya berpura-pura sakit parah. 'Hanya hati kera yang bisa menyembuhkanku,' rintihnya. Dan buaya yang lemah hati itu akhirnya menurut." },
      { illustrationSeed: "monkey-croc-6", textEn: "'Friend monkey!' he called the next morning. 'My wife has cooked a feast to thank you for the fruit. Climb on my back, and I shall carry you across to our home!'", textId: "'Sahabatku kera!' panggilnya keesokan pagi. 'Istriku memasak jamuan untuk berterima kasih atas buah-buahmu. Naiklah ke punggungku, akan kubawa kau ke rumah kami di seberang!'" },
      { illustrationSeed: "monkey-croc-7", textEn: "The monkey, delighted, hopped onto the crocodile's back. But in the middle of the river, where the water ran deepest, the crocodile began to sink — and told the truth.", textId: "Kera dengan senang hati melompat ke punggung buaya. Namun di tengah sungai, di bagian air yang paling dalam, buaya mulai menenggelamkan diri — dan mengakui yang sebenarnya." },
      { illustrationSeed: "monkey-croc-8", textEn: "'Forgive me, friend. My wife is ill, and she says only your heart can cure her.' The monkey's blood ran cold — but his clever mind stayed warm, and it worked faster than fear.", textId: "'Maafkan aku, kawan. Istriku sakit, dan katanya hanya hatimu yang bisa menyembuhkannya.' Darah kera serasa membeku — tapi akal cerdiknya tetap hangat, dan bekerja lebih cepat daripada rasa takut." },
      { illustrationSeed: "monkey-croc-9", textEn: "'My heart? Oh, dear friend, why didn't you say so at the tree!' cried the monkey. 'We monkeys never carry our hearts around — they are far too precious! Mine is hanging safely in the jamun tree!'", textId: "'Hatiku? Aduh, sahabatku, mengapa tak bilang dari tadi di pohon!' seru kera. 'Kami para kera tak pernah membawa-bawa hati — terlalu berharga! Hatiku kugantung aman di pohon jamblang!'" },
      { illustrationSeed: "monkey-croc-10", textEn: "'Then we must go back for it at once!' said the crocodile, and he turned around and swam swiftly back to the tree.", textId: "'Kalau begitu kita harus kembali mengambilnya sekarang juga!' kata buaya, lalu ia berbalik dan berenang cepat kembali ke pohon." },
      { illustrationSeed: "monkey-croc-11", textEn: "The moment they touched the bank, the monkey leapt high into his tree and looked down. 'Foolish friend! Who ever heard of a heart hanging in a tree? A friend who plots against a friend loses the fruit AND the friendship!'", textId: "Begitu menyentuh tepian, kera melompat tinggi ke pohonnya dan menoleh ke bawah. 'Sahabat yang bodoh! Mana ada hati digantung di pohon? Sahabat yang berkhianat kehilangan buahnya DAN persahabatannya!'" },
      { illustrationSeed: "monkey-croc-12", textEn: "The crocodile swam home ashamed, with no heart, no fruit and no friend. And children by that river still learn the double lesson: keep your wits when danger speaks sweetly — and never trade a true friend for anything. The end.", textId: "Buaya berenang pulang dengan malu, tanpa hati, tanpa buah, dan tanpa sahabat. Dan anak-anak di tepi sungai itu masih mempelajari pelajaran gandanya: jaga akalmu saat bahaya berbicara manis — dan jangan pernah menukar sahabat sejati dengan apa pun. Tamat." },
    ],
    quiz: [
      { questionEn: "How did the monkey and crocodile become friends?", questionId: "Bagaimana kera dan buaya bersahabat?", optionsEn: ["The monkey shared his sweet jamun fruit", "They raced across the river", "The crocodile saved the monkey"], optionsId: ["Kera berbagi buah jamblang manisnya", "Mereka berlomba menyeberangi sungai", "Buaya menyelamatkan kera"], correctIndex: 0 },
      { questionEn: "What did the monkey say to save himself?", questionId: "Apa kata kera untuk menyelamatkan diri?", optionsEn: ["That he could not swim", "That his heart was hanging in the jamun tree", "That he was not sweet"], optionsId: ["Bahwa ia tak bisa berenang", "Bahwa hatinya tergantung di pohon jamblang", "Bahwa ia tidak manis"], correctIndex: 1 },
      { questionEn: "What did the crocodile lose in the end?", questionId: "Apa yang hilang dari buaya pada akhirnya?", optionsEn: ["His tail", "The fruit and the friendship", "His house"], optionsId: ["Ekornya", "Buah dan persahabatannya", "Rumahnya"], correctIndex: 1 },
    ],
  },
  {
    slug: "the-empty-pot",
    titleEn: "The Empty Pot",
    titleId: "Pot yang Kosong",
    descriptionEn: "The Emperor will choose his heir with a single flower seed. A whole kingdom grows glorious blooms — except one boy, whose pot stays empty.",
    descriptionId: "Kaisar akan memilih penerusnya dengan sebutir benih bunga. Seluruh negeri menumbuhkan bunga-bunga indah — kecuali satu anak, yang potnya tetap kosong.",
    categorySlug: "world-cultures",
    authorSlug: "david-lee",
    coverEmoji: "🌱",
    coverPalette: "meadow",
    ageMin: 4,
    ageMax: 10,
    isPremium: false,
    pages: [
      { illustrationSeed: "empty-pot-1", textEn: "Long ago in China there lived an old Emperor who loved flowers more than gold. He had no child of his own, and the time had come to choose who would rule after him.", textId: "Dahulu kala di Tiongkok hiduplah seorang Kaisar tua yang mencintai bunga melebihi emas. Ia tak punya anak, dan tibalah waktunya memilih siapa yang akan memerintah setelahnya." },
      { illustrationSeed: "empty-pot-2", textEn: "So the Emperor made a proclamation: 'Every child in the kingdom shall receive one seed from my own hand. Whoever grows the finest flower in one year shall be my heir.'", textId: "Maka Kaisar mengeluarkan pengumuman: 'Setiap anak di negeri ini akan menerima sebutir benih dari tanganku sendiri. Siapa yang menumbuhkan bunga terindah dalam satu tahun akan menjadi penerusku.'" },
      { illustrationSeed: "empty-pot-3", textEn: "A boy named Ping was among the thousands who came. Ping loved gardening with his whole heart — everything he planted seemed to wake up and dance. He carried his seed home like a treasure.", textId: "Seorang anak bernama Ping ada di antara ribuan anak yang datang. Ping mencintai berkebun dengan segenap hatinya — apa pun yang ia tanam seakan bangun dan menari. Ia membawa pulang benihnya bagai harta karun." },
      { illustrationSeed: "empty-pot-4", textEn: "He chose his best pot, his richest soil, and planted the seed with the gentlest fingers in the kingdom. He watered it every morning. And he waited.", textId: "Ia memilih pot terbaiknya, tanah tersuburnya, dan menanam benih itu dengan jari-jari terlembut di seluruh negeri. Ia menyiraminya setiap pagi. Lalu ia menunggu." },
      { illustrationSeed: "empty-pot-5", textEn: "Nothing grew. Ping moved the pot into the sun. Nothing. He changed the soil, he sang to it, he checked it by moonlight. Still nothing — not even the smallest green tip.", textId: "Tak ada yang tumbuh. Ping memindahkan pot ke bawah matahari. Nihil. Ia mengganti tanah, bernyanyi untuknya, memeriksanya di bawah cahaya bulan. Tetap nihil — bahkan pucuk hijau terkecil pun tidak." },
      { illustrationSeed: "empty-pot-6", textEn: "Meanwhile, all over the kingdom, the other children whispered of their wonderful flowers. 'Mine is red as fire!' 'Mine is taller than my father!' Ping's heart sank lower every day.", textId: "Sementara itu, di seluruh negeri, anak-anak lain berbisik tentang bunga mereka yang menakjubkan. 'Punyaku merah seperti api!' 'Punyaku lebih tinggi dari ayahku!' Hati Ping tenggelam semakin dalam setiap hari." },
      { illustrationSeed: "empty-pot-7", textEn: "The year ended. The children marched to the palace carrying pots bursting with magnificent blooms — crimson, gold, purple, white. And Ping walked among them carrying... an empty pot.", textId: "Tahun pun berakhir. Anak-anak berbaris ke istana membawa pot yang penuh bunga-bunga megah — merah tua, emas, ungu, putih. Dan Ping berjalan di antara mereka membawa... pot yang kosong." },
      { illustrationSeed: "empty-pot-8", textEn: "'Why do you bring an empty pot?' the other children laughed. Ping's cheeks burned, but he answered quietly: 'I did everything I could. This is the truth of what grew.'", textId: "'Mengapa kau membawa pot kosong?' anak-anak lain tertawa. Pipi Ping memerah, tapi ia menjawab pelan: 'Aku sudah berusaha sebisaku. Inilah yang sebenarnya tumbuh.'" },
      { illustrationSeed: "empty-pot-9", textEn: "The Emperor walked slowly down the long line of glorious flowers, his face growing stranger and sadder at every step. Then he stopped — in front of the empty pot.", textId: "Kaisar berjalan pelan menyusuri barisan panjang bunga-bunga indah itu, wajahnya semakin aneh dan sedih di setiap langkah. Lalu ia berhenti — di depan pot yang kosong." },
      { illustrationSeed: "empty-pot-10", textEn: "'What is your name, child?' — 'Ping, Your Majesty. I am sorry. I tried my very best, but your seed would not grow.' The Emperor's eyes began to shine.", textId: "'Siapa namamu, nak?' — 'Ping, Yang Mulia. Maafkan saya. Saya sudah berusaha sebaik mungkin, tapi benih Paduka tidak mau tumbuh.' Mata Kaisar mulai berbinar." },
      { illustrationSeed: "empty-pot-11", textEn: "The Emperor turned to the crowd and raised his voice: 'Hear me! The seeds I gave were all COOKED. Not one of them could ever grow. Yet only one child has brought me the truth!'", textId: "Kaisar berbalik ke arah kerumunan dan mengangkat suaranya: 'Dengarlah! Semua benih yang kubagikan sudah DIREBUS. Tak satu pun bisa tumbuh. Namun hanya satu anak yang membawakan kepadaku kejujuran!'" },
      { illustrationSeed: "empty-pot-12", textEn: "'Courage to tell the truth when it is hard — that is the flower I was looking for.' And so Ping, the boy with the empty pot, became the Emperor's heir — and years later, the kingdom's most honest and beloved ruler. The end.", textId: "'Keberanian berkata jujur saat itu sulit — itulah bunga yang kucari.' Maka Ping, anak dengan pot kosong itu, menjadi penerus Kaisar — dan bertahun-tahun kemudian, menjadi pemimpin paling jujur dan paling dicintai di negeri itu. Tamat." },
    ],
    quiz: [
      { questionEn: "Why did nothing grow from Ping's seed?", questionId: "Mengapa benih Ping tidak tumbuh?", optionsEn: ["He forgot to water it", "All the seeds had been cooked", "He used bad soil"], optionsId: ["Ia lupa menyiramnya", "Semua benih sudah direbus", "Tanahnya jelek"], correctIndex: 1 },
      { questionEn: "Where did the other children's flowers come from?", questionId: "Dari mana bunga anak-anak lain berasal?", optionsEn: ["From the Emperor's seeds", "Not from the Emperor's seeds — they were not honest", "From a magic garden"], optionsId: ["Dari benih Kaisar", "Bukan dari benih Kaisar — mereka tidak jujur", "Dari kebun ajaib"], correctIndex: 1 },
      { questionEn: "What 'flower' was the Emperor really looking for?", questionId: "'Bunga' apa yang sebenarnya dicari Kaisar?", optionsEn: ["The tallest bloom", "The rarest color", "The courage to tell the truth"], optionsId: ["Bunga tertinggi", "Warna terlangka", "Keberanian untuk berkata jujur"], correctIndex: 2 },
    ],
  },
];
