/**
 * World folk tales — long, read-aloud children's stories (~8–10 minutes each)
 * retold in the platform's own words from classic PUBLIC-DOMAIN folklore from
 * around the world (owner: "cerita anak berkualitas, agak panjang 10 menitan,
 * dari seluruh dunia"). Bilingual EN/ID like the rest of the library, each with
 * a gentle comprehension quiz. Concatenated into STORIES (see stories.ts) so
 * `npm run generate:seed` writes them straight into seed/seed.sql.
 */
import type { Story } from "./stories";

export const WORLD_STORIES: Story[] = [
  {
    slug: "the-lion-and-the-mouse",
    titleEn: "The Lion and the Mouse",
    titleId: "Singa dan Tikus Kecil",
    descriptionEn: "A tiny mouse promises to help a mighty lion — and one day, against all odds, she keeps her word.",
    descriptionId: "Seekor tikus kecil berjanji menolong singa yang perkasa — dan suatu hari, ia benar-benar menepatinya.",
    categorySlug: "moral-stories",
    authorSlug: "axto-creative-team",
    coverEmoji: "🦁",
    coverPalette: "sunrise",
    ageMin: 3,
    ageMax: 8,
    isPremium: false,
    pages: [
      { illustrationSeed: "lion-mouse-1", textEn: "Deep in the golden grasslands of Africa lived a great lion. He was the strongest animal for miles around, and when he roared, even the wind seemed to hold its breath.", textId: "Jauh di padang rumput keemasan Afrika, hiduplah seekor singa besar. Ia hewan terkuat sejauh mata memandang, dan ketika ia mengaum, angin pun seakan menahan napas." },
      { illustrationSeed: "lion-mouse-2", textEn: "One warm afternoon, the lion lay sleeping under a shady acacia tree, his huge paws stretched out in the soft grass.", textId: "Suatu siang yang hangat, singa itu tertidur di bawah pohon akasia yang rindang, cakar besarnya terjulur di rerumputan lembut." },
      { illustrationSeed: "lion-mouse-3", textEn: "A little mouse, hurrying home with a seed for her supper, did not see the sleeping lion. She scampered right up his warm back — and woke him with a start!", textId: "Seekor tikus kecil yang tergesa pulang membawa biji untuk makan malamnya tak melihat singa yang tidur. Ia berlari tepat ke punggung hangat sang singa — dan membangunkannya!" },
      { illustrationSeed: "lion-mouse-4", textEn: "The lion's giant paw came down and trapped her gently against the ground. 'How dare you wake me!' he growled. The mouse trembled from her whiskers to her tail.", textId: "Cakar raksasa singa turun dan menahannya lembut ke tanah. 'Berani sekali kau membangunkanku!' geramnya. Tikus itu gemetar dari kumis sampai ekornya." },
      { illustrationSeed: "lion-mouse-5", textEn: "'Please, mighty lion, let me go,' she squeaked. 'I am only small, and I meant no harm. If you set me free, perhaps one day I can help you.'", textId: "'Tolong, singa yang perkasa, lepaskan aku,' cicitnya. 'Aku hanya kecil dan tak bermaksud jahat. Jika kau membebaskanku, mungkin suatu hari aku bisa menolongmu.'" },
      { illustrationSeed: "lion-mouse-6", textEn: "The lion laughed a great rumbling laugh. 'You? Help me? What a funny little thought!' But he was in a kind mood, so he lifted his paw and let her go.", textId: "Singa itu tertawa menggelegar. 'Kau? Menolongku? Sungguh lucu!' Namun hatinya sedang baik, maka ia mengangkat cakarnya dan melepaskan tikus itu." },
      { illustrationSeed: "lion-mouse-7", textEn: "'Thank you, thank you!' cried the mouse, and she darted away into the grass, her small heart pounding with relief.", textId: "'Terima kasih, terima kasih!' seru tikus itu, lalu melesat ke rerumputan, jantung kecilnya berdebar lega." },
      { illustrationSeed: "lion-mouse-8", textEn: "Many days passed. Then one evening, hunters came to the grasslands. They spread a strong rope net between the trees, and the great lion walked straight into their trap.", textId: "Berhari-hari berlalu. Lalu suatu senja, pemburu datang ke padang. Mereka membentangkan jaring tali yang kuat di antara pohon, dan singa besar itu berjalan tepat ke perangkap." },
      { illustrationSeed: "lion-mouse-9", textEn: "The more he struggled, the tighter the net held him. He roared and roared, but the ropes would not break. For the first time, the mighty lion felt truly helpless.", textId: "Semakin ia meronta, semakin erat jaring itu mengikatnya. Ia mengaum berkali-kali, tetapi tali itu tak putus. Untuk pertama kalinya, singa perkasa itu merasa benar-benar tak berdaya." },
      { illustrationSeed: "lion-mouse-10", textEn: "Far away, the little mouse heard the desperate roars. 'That is my friend the lion!' she said, and she ran as fast as her tiny legs could carry her.", textId: "Jauh di sana, tikus kecil mendengar aumannya yang putus asa. 'Itu sahabatku, sang singa!' katanya, lalu ia berlari secepat kaki kecilnya bisa membawanya." },
      { illustrationSeed: "lion-mouse-11", textEn: "She reached the net and began to gnaw — nibble, nibble, nibble — with her sharp little teeth. One rope snapped. Then another. Then another.", textId: "Ia sampai di jaring dan mulai menggerogoti — kriuk, kriuk, kriuk — dengan gigi kecilnya yang tajam. Satu tali putus. Lalu satu lagi. Lalu satu lagi." },
      { illustrationSeed: "lion-mouse-12", textEn: "At last the net fell open, and the great lion stepped free. He looked down at the tiny mouse in wonder. 'You truly did help me,' he said softly.", textId: "Akhirnya jaring itu terbuka, dan singa besar melangkah bebas. Ia menunduk memandang tikus mungil itu dengan takjub. 'Kau sungguh menolongku,' katanya lembut." },
      { illustrationSeed: "lion-mouse-13", textEn: "From that day on, the lion and the mouse were the closest of friends. And the lion never again laughed at anyone for being small.", textId: "Sejak hari itu, singa dan tikus menjadi sahabat terdekat. Dan singa tak pernah lagi menertawakan siapa pun karena tubuhnya kecil." },
      { illustrationSeed: "lion-mouse-14", textEn: "For kindness is never wasted, and even the smallest friend can do the greatest thing. The end.", textId: "Sebab kebaikan tak pernah sia-sia, dan sahabat sekecil apa pun bisa melakukan hal terbesar. Tamat." },
    ],
    quiz: [
      { questionEn: "Why did the lion let the mouse go?", questionId: "Mengapa singa melepaskan tikus?", optionsEn: ["He was hungry", "He was in a kind mood", "The mouse ran away", "He was afraid"], optionsId: ["Ia lapar", "Hatinya sedang baik", "Tikus melarikan diri", "Ia takut"], correctIndex: 1 },
      { questionEn: "How did the mouse save the lion?", questionId: "Bagaimana tikus menyelamatkan singa?", optionsEn: ["She roared loudly", "She called the hunters", "She gnawed through the net", "She dug a hole"], optionsId: ["Ia mengaum keras", "Ia memanggil pemburu", "Ia menggerogoti jaring", "Ia menggali lubang"], correctIndex: 2 },
      { questionEn: "What is the lesson of the story?", questionId: "Apa pelajaran dari cerita ini?", optionsEn: ["Big is always best", "Kindness is never wasted", "Never sleep outside", "Run fast"], optionsId: ["Besar selalu terbaik", "Kebaikan tak pernah sia-sia", "Jangan tidur di luar", "Berlari cepat"], correctIndex: 1 },
    ],
  },
  {
    slug: "momotaro-the-peach-boy",
    titleEn: "Momotaro, the Peach Boy",
    titleId: "Momotaro, Anak dari Buah Persik",
    descriptionEn: "A brave boy born from a giant peach sets off with three animal friends to bring peace back to his island.",
    descriptionId: "Anak pemberani yang lahir dari buah persik raksasa berpetualang bersama tiga sahabat hewan untuk membawa kedamaian kembali ke pulaunya.",
    categorySlug: "adventure",
    authorSlug: "axto-creative-team",
    coverEmoji: "🍑",
    coverPalette: "sunrise",
    ageMin: 4,
    ageMax: 9,
    isPremium: false,
    pages: [
      { illustrationSeed: "momo-1", textEn: "Long ago in Japan, an old woodcutter and his wife lived at the edge of a quiet village. They were kind and gentle, but they had no children, and their little house often felt empty.", textId: "Dahulu kala di Jepang, seorang penebang kayu tua dan istrinya tinggal di tepi desa yang tenang. Mereka baik dan lembut, tetapi tak punya anak, dan rumah kecil mereka sering terasa sepi." },
      { illustrationSeed: "momo-2", textEn: "One morning, while the old woman washed clothes by the river, an enormous peach came bobbing down the water — the biggest peach she had ever seen.", textId: "Suatu pagi, ketika nenek mencuci pakaian di sungai, sebuah buah persik raksasa hanyut di air — persik terbesar yang pernah ia lihat." },
      { illustrationSeed: "momo-3", textEn: "She carried it home, and when the old man raised his knife to slice it, the peach split open by itself — and inside sat a healthy, laughing baby boy!", textId: "Ia membawanya pulang, dan ketika kakek mengangkat pisau untuk membelahnya, persik itu terbuka dengan sendirinya — dan di dalamnya duduk seorang bayi laki-laki yang sehat dan tertawa!" },
      { illustrationSeed: "momo-4", textEn: "'A gift from heaven!' they cried with joy. They named him Momotaro, which means Peach Boy, and raised him with all their love.", textId: "'Anugerah dari langit!' seru mereka penuh gembira. Mereka menamainya Momotaro, yang berarti Anak Persik, dan membesarkannya dengan segenap cinta." },
      { illustrationSeed: "momo-5", textEn: "Momotaro grew strong and kind. But across the sea lay Ogre Island, where fierce ogres sailed out to trouble the villages and take what was not theirs.", textId: "Momotaro tumbuh kuat dan baik hati. Namun di seberang laut ada Pulau Raksasa, tempat para raksasa buas berlayar untuk mengganggu desa dan merampas yang bukan milik mereka." },
      { illustrationSeed: "momo-6", textEn: "When he was old enough, Momotaro said, 'I will sail to Ogre Island and ask the ogres to stop, so our people can live in peace.' His parents packed him millet dumplings for the journey.", textId: "Ketika cukup besar, Momotaro berkata, 'Aku akan berlayar ke Pulau Raksasa dan meminta mereka berhenti, agar rakyat kita hidup damai.' Orang tuanya membekali kue millet untuk perjalanannya." },
      { illustrationSeed: "momo-7", textEn: "On the road he met a spotted dog. 'Where are you going, Momotaro?' 'To Ogre Island, for peace.' 'Give me a dumpling and I will come too!' So they walked on together.", textId: "Di jalan ia bertemu anjing belang. 'Mau ke mana, Momotaro?' 'Ke Pulau Raksasa, demi kedamaian.' 'Beri aku sekue dan aku ikut!' Maka mereka berjalan bersama." },
      { illustrationSeed: "momo-8", textEn: "Next came a clever monkey, and then a bright-eyed pheasant. Each shared a dumpling, and each joined the quest. Now they were four brave friends.", textId: "Lalu datang seekor monyet cerdik, dan seekor burung pegar bermata cerah. Masing-masing berbagi kue, dan masing-masing ikut serta. Kini mereka berempat sahabat pemberani." },
      { illustrationSeed: "momo-9", textEn: "They built a little boat and rowed across the wide blue sea. The pheasant flew ahead to scout, the monkey climbed the mast, and the dog watched the waves.", textId: "Mereka membuat perahu kecil dan mendayung menyeberangi laut biru yang luas. Pegar terbang memandu, monyet memanjat tiang, dan anjing mengawasi ombak." },
      { illustrationSeed: "momo-10", textEn: "At last they reached Ogre Island, ringed by tall black walls. The ogres laughed from their fortress. 'Go home, little boy!' they shouted.", textId: "Akhirnya mereka sampai di Pulau Raksasa, dikelilingi tembok hitam yang tinggi. Para raksasa tertawa dari benteng mereka. 'Pulanglah, anak kecil!' teriak mereka." },
      { illustrationSeed: "momo-11", textEn: "But Momotaro and his friends worked as a team. The pheasant swooped and distracted the ogres, the monkey unlocked the gate, and the dog and Momotaro walked bravely inside.", textId: "Namun Momotaro dan sahabatnya bekerja sebagai satu tim. Pegar menukik mengalihkan perhatian raksasa, monyet membuka gerbang, dan anjing bersama Momotaro melangkah masuk dengan berani." },
      { illustrationSeed: "momo-12", textEn: "The ogre king was surprised by their courage and teamwork. 'We surrender!' he said. 'We are sorry for the trouble we caused.'", textId: "Raja raksasa terkejut oleh keberanian dan kerja sama mereka. 'Kami menyerah!' katanya. 'Kami minta maaf atas kekacauan yang kami buat.'" },
      { illustrationSeed: "momo-13", textEn: "Momotaro did not wish to be cruel. 'Return what you have taken, and promise to trouble the villages no more.' The ogres agreed and gave back every stolen treasure.", textId: "Momotaro tak ingin kejam. 'Kembalikan yang kalian rampas, dan berjanjilah tak lagi mengganggu desa.' Para raksasa setuju dan mengembalikan setiap harta yang mereka curi." },
      { illustrationSeed: "momo-14", textEn: "Momotaro and his three friends sailed home as heroes. The village celebrated, and the old couple hugged their brave Peach Boy with happy tears.", textId: "Momotaro dan tiga sahabatnya berlayar pulang sebagai pahlawan. Desa bersukacita, dan pasangan tua itu memeluk Anak Persik pemberani mereka dengan air mata bahagia." },
      { illustrationSeed: "momo-15", textEn: "And from that day, the island lived in peace — because Momotaro knew that courage and good friends can solve even the biggest troubles. The end.", textId: "Dan sejak hari itu, pulau itu hidup damai — sebab Momotaro tahu bahwa keberanian dan sahabat yang baik dapat mengatasi masalah terbesar sekalipun. Tamat." },
    ],
    quiz: [
      { questionEn: "Where was Momotaro found?", questionId: "Di mana Momotaro ditemukan?", optionsEn: ["In a basket", "Inside a giant peach", "Under a tree", "In a boat"], optionsId: ["Dalam keranjang", "Di dalam persik raksasa", "Di bawah pohon", "Di perahu"], correctIndex: 1 },
      { questionEn: "Who joined Momotaro on his journey?", questionId: "Siapa yang menemani Momotaro?", optionsEn: ["A dog, a monkey, and a pheasant", "Three ogres", "His teacher", "No one"], optionsId: ["Anjing, monyet, dan pegar", "Tiga raksasa", "Gurunya", "Tak seorang pun"], correctIndex: 0 },
      { questionEn: "How did they defeat the ogres?", questionId: "Bagaimana mereka mengalahkan raksasa?", optionsEn: ["By fighting alone", "With teamwork", "By running away", "With magic"], optionsId: ["Bertarung sendiri", "Dengan kerja sama", "Dengan melarikan diri", "Dengan sihir"], correctIndex: 1 },
    ],
  },
  {
    slug: "anansi-and-the-pot-of-wisdom",
    titleEn: "Anansi and the Pot of Wisdom",
    titleId: "Anansi dan Periuk Kebijaksanaan",
    descriptionEn: "A clever spider tries to keep all the world's wisdom for himself — and learns something wiser than he expected.",
    descriptionId: "Laba-laba cerdik berusaha menyimpan semua kebijaksanaan dunia untuk dirinya sendiri — lalu belajar sesuatu yang lebih bijak dari dugaannya.",
    categorySlug: "moral-stories",
    authorSlug: "axto-creative-team",
    coverEmoji: "🕷️",
    coverPalette: "forest",
    ageMin: 4,
    ageMax: 9,
    isPremium: false,
    pages: [
      { illustrationSeed: "anansi-1", textEn: "In the warm forests of West Africa, there lived a clever spider named Anansi. He loved to know things — more than anyone else in the whole world.", textId: "Di hutan hangat Afrika Barat, hiduplah laba-laba cerdik bernama Anansi. Ia suka mengetahui banyak hal — lebih dari siapa pun di seluruh dunia." },
      { illustrationSeed: "anansi-2", textEn: "One day Anansi had an idea. 'If I gather ALL the wisdom in the world into one pot,' he thought, 'then I will be the wisest of all, and everyone will need me.'", textId: "Suatu hari Anansi punya gagasan. 'Jika kukumpulkan SEMUA kebijaksanaan dunia ke dalam satu periuk,' pikirnya, 'aku akan menjadi yang paling bijak, dan semua orang membutuhkanku.'" },
      { illustrationSeed: "anansi-3", textEn: "So he traveled far and wide, collecting wise sayings, clever ideas, and useful knowledge, and he poured every drop into a great clay pot.", textId: "Maka ia mengembara jauh, mengumpulkan kata-kata bijak, ide cerdas, dan pengetahuan berguna, lalu menuang setiap tetesnya ke dalam periuk tanah liat yang besar." },
      { illustrationSeed: "anansi-4", textEn: "When the pot was full, Anansi wanted to hide it where no one could ever reach it. 'I will keep it at the very top of the tallest tree,' he decided.", textId: "Ketika periuk itu penuh, Anansi ingin menyembunyikannya di tempat yang tak terjangkau siapa pun. 'Akan kusimpan di puncak pohon tertinggi,' putusnya." },
      { illustrationSeed: "anansi-5", textEn: "He tied the heavy pot to the front of his belly and began to climb. But the pot kept bumping against the trunk and getting in his way.", textId: "Ia mengikat periuk berat itu di depan perutnya dan mulai memanjat. Namun periuk itu terus terbentur batang pohon dan menghalangi jalannya." },
      { illustrationSeed: "anansi-6", textEn: "Again and again he slipped back down. The pot was simply too big and awkward to carry up the front of him. Anansi grew tired and cross.", textId: "Berulang kali ia melorot turun. Periuk itu terlalu besar dan menyusahkan untuk dibawa di depan tubuhnya. Anansi menjadi lelah dan kesal." },
      { illustrationSeed: "anansi-7", textEn: "Down below, his young son had been watching quietly. 'Father,' he called up, 'wouldn't it be easier to tie the pot on your BACK? Then you could climb freely.'", textId: "Di bawah, anaknya yang kecil memperhatikan dengan tenang. 'Ayah,' serunya, 'bukankah lebih mudah mengikat periuk di PUNGGUNG? Agar Ayah bisa memanjat dengan leluasa.'" },
      { illustrationSeed: "anansi-8", textEn: "Anansi stopped. The idea was so simple — and so clever — and it had come from his little son, not from the great pot of wisdom at all.", textId: "Anansi terdiam. Gagasan itu begitu sederhana — dan begitu cerdas — dan datang dari anak kecilnya, bukan dari periuk kebijaksanaan yang besar itu." },
      { illustrationSeed: "anansi-9", textEn: "'I gathered all the wisdom in the world,' Anansi said slowly, 'yet my own son knew something I did not. Wisdom cannot belong to just one person.'", textId: "'Aku mengumpulkan semua kebijaksanaan dunia,' kata Anansi perlahan, 'namun anakku sendiri tahu sesuatu yang tak kuketahui. Kebijaksanaan tak bisa menjadi milik satu orang saja.'" },
      { illustrationSeed: "anansi-10", textEn: "In that moment Anansi understood. He lifted the pot high and let it tip. The wisdom spilled out and scattered on the wind, drifting to every corner of the earth.", textId: "Saat itu Anansi mengerti. Ia mengangkat periuk itu tinggi-tinggi dan menumpahkannya. Kebijaksanaan tumpah dan berhamburan tertiup angin, melayang ke setiap sudut bumi." },
      { illustrationSeed: "anansi-11", textEn: "That is why, to this day, a little bit of wisdom can be found in everyone — in the old and the young, the big and the small.", textId: "Itulah sebabnya, hingga kini, sedikit kebijaksanaan bisa ditemukan pada setiap orang — pada yang tua dan yang muda, yang besar dan yang kecil." },
      { illustrationSeed: "anansi-12", textEn: "And Anansi learned the wisest lesson of all: that we grow wiser not by keeping knowledge to ourselves, but by sharing it. The end.", textId: "Dan Anansi belajar pelajaran paling bijak: bahwa kita menjadi lebih bijak bukan dengan menyimpan pengetahuan sendiri, melainkan dengan membagikannya. Tamat." },
    ],
    quiz: [
      { questionEn: "What did Anansi try to collect?", questionId: "Apa yang Anansi coba kumpulkan?", optionsEn: ["Gold coins", "All the wisdom in the world", "Ripe fruit", "Spider webs"], optionsId: ["Koin emas", "Semua kebijaksanaan dunia", "Buah matang", "Jaring laba-laba"], correctIndex: 1 },
      { questionEn: "Who gave Anansi the clever idea?", questionId: "Siapa yang memberi Anansi ide cerdas?", optionsEn: ["A wise king", "His young son", "A bird", "No one"], optionsId: ["Raja bijak", "Anaknya yang kecil", "Seekor burung", "Tak seorang pun"], correctIndex: 1 },
      { questionEn: "What did Anansi learn?", questionId: "Apa yang Anansi pelajari?", optionsEn: ["To keep everything", "That wisdom grows by sharing", "To climb faster", "To stay quiet"], optionsId: ["Menyimpan segalanya", "Kebijaksanaan tumbuh dengan berbagi", "Memanjat lebih cepat", "Diam saja"], correctIndex: 1 },
    ],
  },
  {
    slug: "the-fisherman-and-the-golden-fish",
    titleEn: "The Fisherman and the Golden Fish",
    titleId: "Nelayan dan Ikan Emas",
    descriptionEn: "A kind old fisherman frees a magical fish — but when wishes grow greedy, he learns what truly matters.",
    descriptionId: "Nelayan tua yang baik hati membebaskan ikan ajaib — namun ketika permintaan berubah tamak, ia belajar apa yang sungguh berharga.",
    categorySlug: "moral-stories",
    authorSlug: "axto-creative-team",
    coverEmoji: "🐟",
    coverPalette: "ocean",
    ageMin: 4,
    ageMax: 9,
    isPremium: false,
    pages: [
      { illustrationSeed: "gfish-1", textEn: "By the shore of a wide grey sea lived a poor old fisherman and his wife, in a tiny hut with a leaky roof and one old fishing net.", textId: "Di tepi laut kelabu yang luas, tinggallah nelayan tua yang miskin dan istrinya, di gubuk kecil beratap bocor dengan satu jala tua." },
      { illustrationSeed: "gfish-2", textEn: "One morning the fisherman cast his net and pulled up something that shimmered like sunlight — a beautiful golden fish.", textId: "Suatu pagi nelayan menebar jala dan menarik sesuatu yang berkilau seperti cahaya matahari — seekor ikan emas yang indah." },
      { illustrationSeed: "gfish-3", textEn: "To his amazement, the fish spoke. 'Kind fisherman, please let me go, and I will grant you a wish in return.'", textId: "Betapa terkejutnya ia, ikan itu berbicara. 'Nelayan yang baik, tolong lepaskan aku, dan aku akan mengabulkan satu permintaanmu.'" },
      { illustrationSeed: "gfish-4", textEn: "The fisherman had a gentle heart. 'You need no reward, little fish. Go home to your family.' And he slipped the golden fish back into the waves.", textId: "Nelayan itu berhati lembut. 'Kau tak perlu memberi imbalan, ikan kecil. Pulanglah ke keluargamu.' Dan ia melepas ikan emas itu kembali ke ombak." },
      { illustrationSeed: "gfish-5", textEn: "When he told his wife, she frowned. 'You foolish man! Go back and ask for a fine new loaf of bread — ours is stale.'", textId: "Ketika ia bercerita pada istrinya, sang istri mengernyit. 'Suami bodoh! Kembalilah dan minta sepotong roti baru yang enak — roti kita sudah basi.'" },
      { illustrationSeed: "gfish-6", textEn: "The fisherman called the fish, and at once fresh warm bread appeared on their table. But the next day, his wife wanted more.", textId: "Nelayan memanggil ikan itu, dan seketika roti hangat yang segar muncul di meja mereka. Namun keesokan harinya, istrinya ingin lebih." },
      { illustrationSeed: "gfish-7", textEn: "'Ask for a new house!' she said. So he did, and their leaky hut became a snug cottage with a solid roof and a warm fire.", textId: "'Minta rumah baru!' katanya. Maka ia melakukannya, dan gubuk bocor mereka menjadi pondok nyaman beratap kokoh dengan perapian yang hangat." },
      { illustrationSeed: "gfish-8", textEn: "But a cottage was not enough. 'Now ask for a grand mansion, with servants and gardens!' Again the fish granted it. Yet still she was not happy.", textId: "Namun pondok itu tak cukup. 'Sekarang minta rumah megah, dengan pelayan dan taman!' Lagi-lagi ikan itu mengabulkannya. Namun sang istri tetap tak bahagia." },
      { illustrationSeed: "gfish-9", textEn: "'I do not want to be rich,' she declared. 'I want to be Queen of all the land!' The fisherman's heart sank, but he went to the shore once more.", textId: "'Aku tak mau hanya kaya,' katanya. 'Aku ingin menjadi Ratu seluruh negeri!' Hati nelayan itu tenggelam, tetapi ia pergi ke pantai sekali lagi." },
      { illustrationSeed: "gfish-10", textEn: "The sea had turned dark and stormy. The golden fish rose from the churning waves. 'What does she wish for now?' it asked quietly.", textId: "Laut menjadi gelap dan bergolak. Ikan emas muncul dari ombak yang bergemuruh. 'Apa lagi yang ia inginkan sekarang?' tanyanya perlahan." },
      { illustrationSeed: "gfish-11", textEn: "'She wishes to be Queen,' the fisherman whispered, ashamed. The fish looked at him with sad, wise eyes, then vanished beneath the water without a word.", textId: "'Ia ingin menjadi Ratu,' bisik nelayan itu dengan malu. Ikan itu menatapnya dengan mata sedih nan bijak, lalu lenyap di bawah air tanpa sepatah kata." },
      { illustrationSeed: "gfish-12", textEn: "When the fisherman walked home, the mansion was gone. The gardens were gone. There stood only their tiny old hut, with its leaky roof, just as before.", textId: "Ketika nelayan pulang, rumah megah itu lenyap. Tamannya lenyap. Yang tersisa hanya gubuk tua kecil mereka, dengan atap bocornya, persis seperti dulu." },
      { illustrationSeed: "gfish-13", textEn: "His wife sat quietly by the door. For the first time in a long while, she looked at all they still had — each other, a roof, and the wide kind sea.", textId: "Istrinya duduk diam di dekat pintu. Untuk pertama kalinya sejak lama, ia memandang semua yang masih mereka miliki — satu sama lain, sebuah atap, dan laut yang luas dan ramah." },
      { illustrationSeed: "gfish-14", textEn: "'I am sorry,' she said softly. 'I forgot to be thankful.' And from that day they lived simply and gratefully, and were happier than any king or queen. The end.", textId: "'Maafkan aku,' katanya lirih. 'Aku lupa bersyukur.' Dan sejak hari itu mereka hidup sederhana dan penuh syukur, lebih bahagia dari raja atau ratu mana pun. Tamat." },
    ],
    quiz: [
      { questionEn: "Why did the fisherman first let the fish go?", questionId: "Mengapa nelayan mula-mula melepas ikan itu?", optionsEn: ["He wasn't hungry", "He had a kind heart", "The fish was too small", "He was afraid"], optionsId: ["Ia tak lapar", "Ia berhati baik", "Ikannya terlalu kecil", "Ia takut"], correctIndex: 1 },
      { questionEn: "What happened when the wife grew greedy?", questionId: "Apa yang terjadi saat istrinya menjadi tamak?", optionsEn: ["She became Queen", "Everything vanished", "The fish gave more", "Nothing changed"], optionsId: ["Ia jadi Ratu", "Semuanya lenyap", "Ikan memberi lebih", "Tak ada yang berubah"], correctIndex: 1 },
      { questionEn: "What did the wife finally learn?", questionId: "Apa yang akhirnya dipelajari istrinya?", optionsEn: ["To wish for more", "To be thankful", "To catch fish", "To build houses"], optionsId: ["Meminta lebih banyak", "Bersyukur", "Menangkap ikan", "Membangun rumah"], correctIndex: 1 },
    ],
  },
  {
    slug: "the-magic-paintbrush",
    titleEn: "The Magic Paintbrush",
    titleId: "Kuas Ajaib",
    descriptionEn: "A poor but generous boy is given a paintbrush that brings drawings to life — and uses its magic to help everyone but the greedy.",
    descriptionId: "Anak miskin yang murah hati diberi kuas yang menghidupkan gambar — dan memakai keajaibannya untuk menolong semua orang, kecuali yang tamak.",
    categorySlug: "fairy-tales",
    authorSlug: "axto-creative-team",
    coverEmoji: "🖌️",
    coverPalette: "sunrise",
    ageMin: 4,
    ageMax: 9,
    isPremium: false,
    pages: [
      { illustrationSeed: "brush-1", textEn: "In a village in old China lived a poor boy named Ma Liang. He had no paints and no brush, but more than anything in the world, he longed to draw.", textId: "Di sebuah desa di Tiongkok kuno, tinggallah anak miskin bernama Ma Liang. Ia tak punya cat maupun kuas, tetapi lebih dari apa pun di dunia, ia ingin menggambar." },
      { illustrationSeed: "brush-2", textEn: "He practiced with a twig in the sand and a wet finger on stone. Every bird, every fish, every leaf he drew looked almost ready to move.", textId: "Ia berlatih dengan ranting di pasir dan jari basah di atas batu. Setiap burung, ikan, dan daun yang ia gambar tampak nyaris bergerak." },
      { illustrationSeed: "brush-3", textEn: "One night an old man with a kind, glowing face appeared in his dream. 'You have a good and generous heart, Ma Liang. Here is a gift.'", textId: "Suatu malam, seorang kakek berwajah ramah dan bercahaya muncul dalam mimpinya. 'Hatimu baik dan murah hati, Ma Liang. Ini sebuah hadiah.'" },
      { illustrationSeed: "brush-4", textEn: "When Ma Liang woke, a beautiful paintbrush lay in his hand. He dipped it and painted a crane — and the crane flapped its wings and flew off the paper into the sky!", textId: "Ketika Ma Liang bangun, sebuah kuas indah ada di tangannya. Ia mencelupkannya dan melukis burung bangau — dan bangau itu mengepakkan sayap dan terbang dari kertas ke langit!" },
      { illustrationSeed: "brush-5", textEn: "It was a magic paintbrush: whatever he painted came to life. But Ma Liang remembered his empty stomach and his poor neighbours.", textId: "Itu kuas ajaib: apa pun yang ia lukis menjadi hidup. Namun Ma Liang teringat perutnya yang lapar dan tetangganya yang miskin." },
      { illustrationSeed: "brush-6", textEn: "He did not paint gold for himself. Instead he painted a plough for the farmer, a bucket for the water-carrier, and a warm blanket for a shivering old woman.", textId: "Ia tak melukis emas untuk dirinya. Ia justru melukis bajak untuk petani, ember untuk pembawa air, dan selimut hangat untuk nenek yang kedinginan." },
      { illustrationSeed: "brush-7", textEn: "Soon the whole village had what it needed, and everyone loved the kind boy with the magic brush.", textId: "Tak lama, seluruh desa memiliki apa yang mereka butuhkan, dan semua orang menyayangi anak baik dengan kuas ajaib itu." },
      { illustrationSeed: "brush-8", textEn: "But news of the brush reached a greedy rich lord. He sent his guards to seize Ma Liang and lock him in a cold stone room. 'Paint me a mountain of gold!' he demanded.", textId: "Namun kabar tentang kuas itu sampai ke telinga tuan tanah yang tamak. Ia mengirim pengawal menangkap Ma Liang dan menguncinya di ruang batu yang dingin. 'Lukiskan aku gunung emas!' perintahnya." },
      { illustrationSeed: "brush-9", textEn: "Ma Liang thought carefully. He agreed — but he was clever. First he painted a wide blue sea. 'Where is my gold?' snapped the lord.", textId: "Ma Liang berpikir hati-hati. Ia setuju — tetapi ia cerdik. Pertama ia melukis laut biru yang luas. 'Mana emasku?' bentak sang tuan tanah." },
      { illustrationSeed: "brush-10", textEn: "'The gold is on an island across the water,' said Ma Liang, and he painted a fine ship. The greedy lord and his guards jumped aboard at once.", textId: "'Emasnya ada di pulau seberang,' kata Ma Liang, lalu ia melukis kapal yang bagus. Tuan tanah tamak dan pengawalnya langsung melompat naik." },
      { illustrationSeed: "brush-11", textEn: "'Faster! Faster!' cried the lord. So Ma Liang painted a strong wind. He painted it stronger, and stronger — until the waves rose and carried the ship far, far over the horizon.", textId: "'Lebih cepat! Lebih cepat!' teriak sang tuan tanah. Maka Ma Liang melukis angin kencang. Ia melukisnya makin kencang, makin kencang — hingga ombak meninggi dan membawa kapal itu jauh, jauh melewati cakrawala." },
      { illustrationSeed: "brush-12", textEn: "The greedy lord was never seen troubling the village again. Ma Liang returned home free, and to the people who were kind and worked hard.", textId: "Tuan tanah tamak itu tak pernah lagi terlihat mengganggu desa. Ma Liang pulang dengan bebas, kembali kepada orang-orang yang baik dan pekerja keras." },
      { illustrationSeed: "brush-13", textEn: "For the rest of his days, Ma Liang used his magic brush only to help those in need — for he knew that a gift is truest when it is shared. The end.", textId: "Sepanjang sisa hidupnya, Ma Liang memakai kuas ajaibnya hanya untuk menolong yang membutuhkan — sebab ia tahu bahwa sebuah anugerah paling berarti ketika dibagikan. Tamat." },
    ],
    quiz: [
      { questionEn: "What did the magic paintbrush do?", questionId: "Apa yang dilakukan kuas ajaib itu?", optionsEn: ["Made things invisible", "Brought drawings to life", "Turned things to gold", "Told stories"], optionsId: ["Membuat benda tak terlihat", "Menghidupkan gambar", "Mengubah benda jadi emas", "Bercerita"], correctIndex: 1 },
      { questionEn: "What did Ma Liang paint for the village?", questionId: "Apa yang Ma Liang lukis untuk desa?", optionsEn: ["Gold for himself", "Tools and blankets to help others", "A castle", "Nothing"], optionsId: ["Emas untuk dirinya", "Alat dan selimut untuk menolong", "Sebuah istana", "Tidak ada"], correctIndex: 1 },
      { questionEn: "How did Ma Liang outwit the greedy lord?", questionId: "Bagaimana Ma Liang mengecoh tuan tanah tamak?", optionsEn: ["He gave him gold", "He painted a storm at sea", "He ran away", "He apologised"], optionsId: ["Memberinya emas", "Melukis badai di laut", "Melarikan diri", "Meminta maaf"], correctIndex: 1 },
    ],
  },
  {
    slug: "stone-soup",
    titleEn: "Stone Soup",
    titleId: "Sup Batu",
    descriptionEn: "Three tired travellers arrive at a village with nothing but a stone — and teach everyone the magic of sharing.",
    descriptionId: "Tiga pengembara lelah tiba di desa hanya dengan sebuah batu — dan mengajarkan semua orang keajaiban berbagi.",
    categorySlug: "friendship",
    authorSlug: "axto-creative-team",
    coverEmoji: "🍲",
    coverPalette: "forest",
    ageMin: 3,
    ageMax: 8,
    isPremium: false,
    pages: [
      { illustrationSeed: "soup-1", textEn: "Three tired travellers walked a long dusty road until they reached a small village at dusk. They were hungry, and they had no food at all.", textId: "Tiga pengembara yang lelah menyusuri jalan berdebu yang panjang hingga tiba di desa kecil saat senja. Mereka lapar, dan sama sekali tak punya makanan." },
      { illustrationSeed: "soup-2", textEn: "They knocked on doors, but times were hard. 'We have nothing to spare,' said each villager, and quietly closed the door.", textId: "Mereka mengetuk pintu-pintu, tetapi masa itu sulit. 'Kami tak punya lebih,' kata setiap warga, lalu menutup pintu perlahan." },
      { illustrationSeed: "soup-3", textEn: "The travellers were not angry. Instead, they smiled. 'Then we shall make Stone Soup, and share it with the whole village!'", textId: "Para pengembara tidak marah. Mereka justru tersenyum. 'Kalau begitu kami akan membuat Sup Batu, dan membaginya dengan seluruh desa!'" },
      { illustrationSeed: "soup-4", textEn: "In the village square they lit a fire, set a big black pot of water to boil, and gently placed one smooth grey stone inside.", textId: "Di alun-alun desa mereka menyalakan api, menjerang periuk hitam besar berisi air, dan meletakkan sebuah batu kelabu yang halus ke dalamnya." },
      { illustrationSeed: "soup-5", textEn: "Curious villagers gathered round. 'Stone soup?' 'Oh yes,' said a traveller, stirring. 'It is delicious — though a pinch of salt would make it even better.'", textId: "Warga yang penasaran berkumpul. 'Sup batu?' 'Oh ya,' kata seorang pengembara sambil mengaduk. 'Rasanya lezat — meski sejumput garam akan membuatnya lebih enak lagi.'" },
      { illustrationSeed: "soup-6", textEn: "'I have salt!' said a woman, and hurried to fetch some. Soon a man said, 'I have a few carrots in my cellar,' and in they went.", textId: "'Aku punya garam!' kata seorang perempuan, lalu bergegas mengambilnya. Tak lama seorang lelaki berkata, 'Aku punya beberapa wortel di gudang,' dan wortel pun dimasukkan." },
      { illustrationSeed: "soup-7", textEn: "'Onions would help,' said a traveller kindly. 'I have onions!' called a boy. Then came potatoes, then barley, then a handful of fresh green herbs.", textId: "'Bawang akan menambah rasa,' kata pengembara dengan ramah. 'Aku punya bawang!' seru seorang anak. Lalu datang kentang, jelai, dan segenggam rempah hijau segar." },
      { illustrationSeed: "soup-8", textEn: "One by one, each villager brought a little of what they had — a cabbage, some beans, a bit of milk — and stirred it into the bubbling pot.", textId: "Satu per satu, tiap warga membawa sedikit yang mereka punya — sebutir kubis, sedikit kacang, seteguk susu — dan mengaduknya ke dalam periuk yang mendidih." },
      { illustrationSeed: "soup-9", textEn: "The smell that rose from the pot was wonderful. Something that had begun with a single stone was becoming a feast for everyone.", textId: "Aroma yang naik dari periuk itu sungguh menggoda. Sesuatu yang bermula dari sebutir batu kini menjadi jamuan untuk semua orang." },
      { illustrationSeed: "soup-10", textEn: "When the soup was ready, the whole village sat together in the square, sharing bowls, bread, and laughter under the first stars.", textId: "Ketika sup matang, seluruh desa duduk bersama di alun-alun, berbagi mangkuk, roti, dan tawa di bawah bintang-bintang pertama." },
      { illustrationSeed: "soup-11", textEn: "'What magic stone makes such a soup?' the villagers asked. The travellers smiled. 'The stone is just a stone. The magic was you — sharing what you had.'", textId: "'Batu ajaib apa yang membuat sup seperti ini?' tanya warga. Para pengembara tersenyum. 'Batu itu hanyalah batu. Keajaibannya adalah kalian — berbagi apa yang kalian punya.'" },
      { illustrationSeed: "soup-12", textEn: "The next morning the travellers walked on, leaving behind a village that had learned the sweetest recipe of all: that a little from everyone becomes plenty for all. The end.", textId: "Keesokan paginya para pengembara melanjutkan perjalanan, meninggalkan desa yang telah belajar resep termanis: bahwa sedikit dari setiap orang menjadi berlimpah untuk semua. Tamat." },
    ],
    quiz: [
      { questionEn: "What did the travellers put in the pot first?", questionId: "Apa yang pertama dimasukkan pengembara ke periuk?", optionsEn: ["A carrot", "A stone", "An onion", "Salt"], optionsId: ["Wortel", "Sebuah batu", "Bawang", "Garam"], correctIndex: 1 },
      { questionEn: "How did the soup become a feast?", questionId: "Bagaimana sup itu menjadi jamuan besar?", optionsEn: ["By magic", "Everyone shared a little food", "The stone grew", "They bought it"], optionsId: ["Dengan sihir", "Semua berbagi sedikit makanan", "Batunya membesar", "Mereka membelinya"], correctIndex: 1 },
      { questionEn: "What was the real 'magic'?", questionId: "Apa 'keajaiban' yang sebenarnya?", optionsEn: ["The stone", "Sharing together", "The big pot", "The fire"], optionsId: ["Batunya", "Berbagi bersama", "Periuk besar", "Apinya"], correctIndex: 1 },
    ],
  },
];
