/**
 * Generates seed/seed.sql from the content in src/content/*.
 * Run with: npm run generate:seed
 *
 * Prints the freshly-generated admin bootstrap password to stdout once —
 * it is never written to a committed file. Log in and change it immediately.
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { CATEGORIES } from '../src/content/categories';
import { AUTHORS } from '../src/content/authors';
import { STORIES } from '../src/content/stories';

function sqlEscape(value: string): string {
  return value.replace(/'/g, "''");
}

function hashPasswordSync(password: string): string {
  const iterations = 100_000; // Cloudflare Workers PBKDF2 ceiling — see src/lib/auth/password.ts
  const salt = crypto.randomBytes(16);
  const hash = crypto.pbkdf2Sync(password, salt, iterations, 32, 'sha256');
  return `pbkdf2$${iterations}$${salt.toString('base64')}$${hash.toString('base64')}`;
}

function randomPassword(): string {
  return crypto.randomBytes(12).toString('base64url');
}

const lines: string[] = [];
const now = Date.now();

lines.push('-- Auto-generated by scripts/generate-seed.ts — do not edit by hand.');
lines.push('-- Re-run `npm run generate:seed` after changing src/content/*.\n');

// --- Categories ---
for (const c of CATEGORIES) {
  const id = `cat_${c.slug}`;
  lines.push(
    `INSERT OR IGNORE INTO categories (id, slug, icon, name_en, name_id, sort_order) VALUES ('${id}', '${c.slug}', '${sqlEscape(c.icon)}', '${sqlEscape(c.nameEn)}', '${sqlEscape(c.nameId)}', ${c.sortOrder});`
  );
}
lines.push('');

// --- Authors ---
for (const a of AUTHORS) {
  const id = `aut_${a.slug}`;
  lines.push(
    `INSERT OR IGNORE INTO authors (id, name, bio, avatar_seed, is_staff, created_at, updated_at) VALUES ('${id}', '${sqlEscape(a.name)}', '${sqlEscape(a.bio)}', '${sqlEscape(a.avatarSeed)}', 1, ${now}, ${now});`
  );
}
lines.push('');

// --- Books, pages, quiz ---
for (const s of STORIES) {
  const bookId = `bok_${s.slug}`;
  const categoryId = `cat_${s.categorySlug}`;
  const authorId = `aut_${s.authorSlug}`;
  lines.push(
    `INSERT OR IGNORE INTO books (id, slug, title_en, title_id, description_en, description_id, category_id, author_id, cover_palette, cover_emoji, age_min, age_max, is_premium, status, page_count, read_count, created_at, updated_at) VALUES ('${bookId}', '${s.slug}', '${sqlEscape(s.titleEn)}', '${sqlEscape(s.titleId)}', '${sqlEscape(s.descriptionEn)}', '${sqlEscape(s.descriptionId)}', '${categoryId}', '${authorId}', '${s.coverPalette}', '${sqlEscape(s.coverEmoji)}', ${s.ageMin}, ${s.ageMax}, ${s.isPremium ? 1 : 0}, 'published', ${s.pages.length}, ${Math.floor(Math.random() * 5000) + 200}, ${now}, ${now});`
  );

  s.pages.forEach((p, i) => {
    const pageId = `pag_${s.slug}_${i + 1}`;
    lines.push(
      `INSERT OR IGNORE INTO book_pages (id, book_id, page_number, illustration_seed, text_en, text_id) VALUES ('${pageId}', '${bookId}', ${i + 1}, '${sqlEscape(p.illustrationSeed)}', '${sqlEscape(p.textEn)}', '${sqlEscape(p.textId)}');`
    );
  });

  s.quiz.forEach((q, i) => {
    const quizId = `qz_${s.slug}_${i + 1}`;
    const optionsEnJson = sqlEscape(JSON.stringify(q.optionsEn));
    const optionsIdJson = sqlEscape(JSON.stringify(q.optionsId));
    lines.push(
      `INSERT OR IGNORE INTO quiz_questions (id, book_id, sort_order, question_en, question_id, options_en_json, options_id_json, correct_index, xp_reward) VALUES ('${quizId}', '${bookId}', ${i + 1}, '${sqlEscape(q.questionEn)}', '${sqlEscape(q.questionId)}', '${optionsEnJson}', '${optionsIdJson}', ${q.correctIndex}, 10);`
    );
  });

  lines.push('');
}

// --- Bootstrap admin account ---
const adminEmail = 'admin@axto.us';
const adminPassword = randomPassword();
const adminHash = hashPasswordSync(adminPassword);
lines.push(
  `INSERT OR IGNORE INTO users (id, name, email, password_hash, role, locale, avatar_seed, plan, created_at, updated_at) VALUES ('usr_admin_seed', 'Admin AXTO', '${adminEmail}', '${adminHash}', 'admin', 'id', 'admin-seed', 'lifetime', ${now}, ${now});`
);

// --- A starter promo code ---
lines.push(
  `INSERT OR IGNORE INTO promo_codes (id, code, discount_percent, max_uses, used_count, active, created_at) VALUES ('promo_welcome10', 'WELCOME10', 10, 1000, 0, 1, ${now});`
);

writeFileSync(path.join(__dirname, '..', 'seed', 'seed.sql'), lines.join('\n') + '\n');

console.log(`Wrote seed/seed.sql (${STORIES.length} books, ${CATEGORIES.length} categories, ${AUTHORS.length} authors).`);
console.log('');
console.log('=== ADMIN BOOTSTRAP CREDENTIALS (shown once, not saved to any file) ===');
console.log(`  email:    ${adminEmail}`);
console.log(`  password: ${adminPassword}`);
console.log('Log in at /login, then change this password immediately from /admin/settings.');
console.log('========================================================================');
